CheckImgLinearity: ColorSwatchPatch Class Reference
ColorSwatchPatch Class Reference
#include <ColorSwatchPatch.h>
Classes
class Private
Public Member Functions
ColorSwatchPatch (double reflectance)
virtual ~ColorSwatchPatch ()
void setReflectance (const double reflectance)
double getReflectance () const
void setMunsellColor (const MunsellColor *munsellColor)
MunsellColor * getMunsellColor () const
void setImage (const QImage *img, const int orgPixXrelFromMask, const int orgPixYrelFromMask)
QString printPatcheImgInfo () const
bool computeAverageRGBpixel (ImagePlugin *imgPlg)
bool haveAverageColor () const
QColor getAverageColor () const
Private Attributes
Private * d
Friends
std::ostream & operator<< (std::ostream &stream, const ColorSwatchPatch &colorSwatchPatch)
Detailed Description
Definition at line 12 of file ColorSwatchPatch.h.
Constructor & Destructor Documentation
ColorSwatchPatch::ColorSwatchPatch (double reflectance)
Definition at line 27 of file ColorSwatchPatch.cpp.
References d, ColorSwatchPatch::Private::mReflectance, ColorSwatchPatch::Private::mRelPixXbegin, and ColorSwatchPatch::Private::mRelPixYbegin.
ColorSwatchPatch::~ColorSwatchPatch () virtual
Definition at line 34 of file ColorSwatchPatch.cpp.
References d.
Member Function Documentation
bool ColorSwatchPatch::computeAverageRGBpixel (ImagePlugin * imgPlg)
Definition at line 70 of file ColorSwatchPatch.cpp.
References ImagePlugin::averagesChannels(), d, FILE_LINE_FUNC_STR, ImagePlugin::makePixelCoord(), ColorSwatchPatch::Private::mAverageRGB, ColorSwatchPatch::Private::mImg, ColorSwatchPatch::Private::mRelPixXbegin, and ColorSwatchPatch::Private::mRelPixYbegin.
Referenced by ColorSwatch::fillPatchesPixelsFromMask().
QColor ColorSwatchPatch::getAverageColor () const
Definition at line 108 of file ColorSwatchPatch.cpp.
References d, and ColorSwatchPatch::Private::mAverageRGB.
Referenced by ColorSwatch::getGraphData().
MunsellColor * ColorSwatchPatch::getMunsellColor () const
Definition at line 56 of file ColorSwatchPatch.cpp.
References d, and ColorSwatchPatch::Private::mMunsellColor.
Referenced by operator<<().
double ColorSwatchPatch::getReflectance () const
Definition at line 46 of file ColorSwatchPatch.cpp.
References d, and ColorSwatchPatch::Private::mReflectance.
Referenced by ColorSwatch::getGraphData(), and operator<<().
bool ColorSwatchPatch::haveAverageColor () const
Definition at line 101 of file ColorSwatchPatch.cpp.
References d, and ColorSwatchPatch::Private::mAverageRGB.
Referenced by printPatcheImgInfo().
QString ColorSwatchPatch::printPatcheImgInfo () const
Definition at line 115 of file ColorSwatchPatch.cpp.
References d, haveAverageColor(), ColorSwatchPatch::Private::mAverageRGB, ColorSwatchPatch::Private::mImg, ColorSwatchPatch::Private::mRelPixXbegin, and ColorSwatchPatch::Private::mRelPixYbegin.
Referenced by operator<<().
void ColorSwatchPatch::setImage (const QImage * img, const int orgPixXrelFromMask, const int orgPixYrelFromMask)
Definition at line 61 of file ColorSwatchPatch.cpp.
References d, ColorSwatchPatch::Private::mImg, ColorSwatchPatch::Private::mRelPixXbegin, and ColorSwatchPatch::Private::mRelPixYbegin.
void ColorSwatchPatch::setMunsellColor (const MunsellColor * munsellColor)
Definition at line 51 of file ColorSwatchPatch.cpp.
References d, and ColorSwatchPatch::Private::mMunsellColor.
void ColorSwatchPatch::setReflectance (const double reflectance)
Definition at line 41 of file ColorSwatchPatch.cpp.
References d, and ColorSwatchPatch::Private::mReflectance.
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & stream, const ColorSwatchPatch & colorSwatchPatch) friend
Definition at line 130 of file ColorSwatchPatch.cpp.
Member Data Documentation
Private* ColorSwatchPatch::d private
Definition at line 37 of file ColorSwatchPatch.h.
Referenced by ColorSwatchPatch(), computeAverageRGBpixel(), getAverageColor(), getMunsellColor(), getReflectance(), haveAverageColor(), printPatcheImgInfo(), setImage(), setMunsellColor(), setReflectance(), and ~ColorSwatchPatch().
The documentation for this class was generated from the following files:
src/ColorSwatchPatch.h
src/ColorSwatchPatch.cpp