CheckImgLinearity: QCPColorScaleAxisRectPrivate Class Reference
QCPColorScaleAxisRectPrivate Class Reference
#include <qcustomplot.h>
Public Member Functions
QCPColorScaleAxisRectPrivate (QCPColorScale *parentColorScale)
Creates a new instance, as a child of parentColorScale.
Public Member Functions inherited from QCPAxisRect
QCPAxisRect (QCustomPlot *parentPlot, bool setupDefaultAxes=true)
Creates a QCPAxisRect instance and sets default values.
virtual ~QCPAxisRect ()
QPixmap background () const
bool backgroundScaled () const
Qt::AspectRatioMode backgroundScaledMode () const
Qt::Orientations rangeDrag () const
Qt::Orientations rangeZoom () const
QCPAxis * rangeDragAxis (Qt::Orientation orientation)
Returns the range drag axis of the orientation provided.
QCPAxis * rangeZoomAxis (Qt::Orientation orientation)
Returns the range zoom axis of the orientation provided.
double rangeZoomFactor (Qt::Orientation orientation)
Returns the range zoom factor of the orientation provided.
void setBackground (const QPixmap &pm)
Sets pm as the axis background pixmap.
void setBackground (const QPixmap &pm, bool scaled, Qt::AspectRatioMode mode=Qt::KeepAspectRatioByExpanding)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Allows setting the background pixmap of the axis rect, whether it shall be scaled and how it shall be scaled in one call.
void setBackground (const QBrush &brush)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Sets brush as the background brush.
void setBackgroundScaled (bool scaled)
Sets whether the axis background pixmap shall be scaled to fit the axis rect or not.
void setBackgroundScaledMode (Qt::AspectRatioMode mode)
If scaling of the axis background pixmap is enabled (setBackgroundScaled), use this function to define whether and how the aspect ratio of the original pixmap passed to setBackground is preserved.
void setRangeDrag (Qt::Orientations orientations)
Sets which axis orientation may be range dragged by the user with mouse interaction.
void setRangeZoom (Qt::Orientations orientations)
Sets which axis orientation may be zoomed by the user with the mouse wheel.
void setRangeDragAxes (QCPAxis *horizontal, QCPAxis *vertical)
Sets the axes whose range will be dragged when setRangeDrag enables mouse range dragging on the QCustomPlot widget.
void setRangeZoomAxes (QCPAxis *horizontal, QCPAxis *vertical)
Sets the axes whose range will be zoomed when setRangeZoom enables mouse wheel zooming on the QCustomPlot widget.
void setRangeZoomFactor (double horizontalFactor, double verticalFactor)
Sets how strong one rotation step of the mouse wheel zooms, when range zoom was activated with setRangeZoom.
void setRangeZoomFactor (double factor)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Sets both the horizontal and vertical zoom factor.
int axisCount (QCPAxis::AxisType type) const
Returns the number of axes on the axis rect side specified with type.
QCPAxis * axis (QCPAxis::AxisType type, int index=0) const
Returns the axis with the given index on the axis rect side specified with type.
QList< QCPAxis * > axes (QCPAxis::AxisTypes types) const
Returns all axes on the axis rect sides specified with types.
QList< QCPAxis * > axes () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Returns all axes of this axis rect.
QCPAxis * addAxis (QCPAxis::AxisType type, QCPAxis *axis=0)
Adds a new axis to the axis rect side specified with type, and returns it.
QList< QCPAxis * > addAxes (QCPAxis::AxisTypes types)
Adds a new axis with addAxis to each axis rect side specified in types.
bool removeAxis (QCPAxis *axis)
Removes the specified axis from the axis rect and deletes it.
QCPLayoutInset * insetLayout () const
Returns the inset layout of this axis rect.
void setupFullAxesBox (bool connectRanges=false)
Convenience function to create an axis on each side that doesn't have any axes yet and set their visibility to true.
QList< QCPAbstractPlottable * > plottables () const
Returns a list of all the plottables that are associated with this axis rect.
QList< QCPGraph * > graphs () const
Returns a list of all the graphs that are associated with this axis rect.
QList< QCPAbstractItem * > items () const
Returns a list of all the items that are associated with this axis rect.
int left () const
Returns the pixel position of the left border of this axis rect.
int right () const
Returns the pixel position of the right border of this axis rect.
int top () const
Returns the pixel position of the top border of this axis rect.
int bottom () const
Returns the pixel position of the bottom border of this axis rect.
int width () const
Returns the pixel width of this axis rect.
int height () const
Returns the pixel height of this axis rect.
QSize size () const
Returns the pixel size of this axis rect.
QPoint topLeft () const
Returns the top left corner of this axis rect in pixels.
QPoint topRight () const
Returns the top right corner of this axis rect in pixels.
QPoint bottomLeft () const
Returns the bottom left corner of this axis rect in pixels.
QPoint bottomRight () const
Returns the bottom right corner of this axis rect in pixels.
QPoint center () const
Returns the center of this axis rect in pixels.
virtual void update (UpdatePhase phase)
This method is called automatically upon replot and doesn't need to be called by users of QCPAxisRect.
virtual QList< QCPLayoutElement * > elements (bool recursive) const
Returns a list of all child elements in this layout element.
Public Member Functions inherited from QCPLayoutElement
QCPLayoutElement (QCustomPlot *parentPlot=0)
Creates an instance of QCPLayoutElement and sets default values.
virtual ~QCPLayoutElement ()
QCPLayout * layout () const
Returns the parent layout of this layout element.
QRect rect () const
Returns the inner rect of this layout element.
QRect outerRect () const
QMargins margins () const
QMargins minimumMargins () const
QCP::MarginSides autoMargins () const
QSize minimumSize () const
QSize maximumSize () const
QCPMarginGroup * marginGroup (QCP::MarginSide side) const
QHash< QCP::MarginSide,
QCPMarginGroup * > marginGroups () const
void setOuterRect (const QRect &rect)
Sets the outer rect of this layout element.
void setMargins (const QMargins &margins)
Sets the margins of this layout element.
void setMinimumMargins (const QMargins &margins)
If setAutoMargins is enabled on some or all margins, this function is used to provide minimum values for those margins.
void setAutoMargins (QCP::MarginSides sides)
Sets on which sides the margin shall be calculated automatically.
void setMinimumSize (const QSize &size)
Sets the minimum size for the inner rect of this layout element.
void setMinimumSize (int width, int height)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Sets the minimum size for the inner rect of this layout element.
void setMaximumSize (const QSize &size)
Sets the maximum size for the inner rect of this layout element.
void setMaximumSize (int width, int height)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Sets the maximum size for the inner rect of this layout element.
void setMarginGroup (QCP::MarginSides sides, QCPMarginGroup *group)
Sets the margin group of the specified margin sides.
virtual QSize minimumSizeHint () const
Returns the minimum size this layout element (the inner rect) may be compressed to.
virtual QSize maximumSizeHint () const
Returns the maximum size this layout element (the inner rect) may be expanded to.
virtual double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const
Layout elements are sensitive to events inside their outer rect.
Public Member Functions inherited from QCPLayerable
QCPLayerable (QCustomPlot *plot, QString targetLayer=QString(), QCPLayerable *parentLayerable=0)
Creates a new QCPLayerable instance.
~QCPLayerable ()
bool visible () const
QCustomPlot * parentPlot () const
QCPLayerable * parentLayerable () const
Returns the parent layerable of this layerable.
QCPLayer * layer () const
bool antialiased () const
void setVisible (bool on)
Sets the visibility of this layerable object.
Q_SLOT bool setLayer (QCPLayer *layer)
Sets the layer of this layerable object.
bool setLayer (const QString &layerName)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Sets the layer of this layerable object by name.
void setAntialiased (bool enabled)
Sets whether this object will be drawn antialiased or not.
bool realVisibility () const
Returns whether this layerable is visible, taking the visibility of the layerable parent and the visibility of the layer this layerable is on into account.
Protected Member Functions
virtual void draw (QCPPainter *painter)
void updateGradientImage ()
Q_SLOT void axisSelectionChanged (QCPAxis::SelectableParts selectedParts)
Q_SLOT void axisSelectableChanged (QCPAxis::SelectableParts selectableParts)
Protected Member Functions inherited from QCPAxisRect
virtual void applyDefaultAntialiasingHint (QCPPainter *painter) const
virtual int calculateAutoMargin (QCP::MarginSide side)
virtual void mousePressEvent (QMouseEvent *event)
This event is called, if the mouse was pressed while being inside the outer rect of this layout element.
virtual void mouseMoveEvent (QMouseEvent *event)
This event is called, if the mouse is moved inside the outer rect of this layout element.
virtual void mouseReleaseEvent (QMouseEvent *event)
This event is called, if the mouse was previously pressed inside the outer rect of this layout element and is now released.
virtual void wheelEvent (QWheelEvent *event)
This event is called, if the mouse wheel is scrolled while the cursor is inside the rect of this layout element.
void drawBackground (QCPPainter *painter)
void updateAxesOffset (QCPAxis::AxisType type)
Protected Member Functions inherited from QCPLayoutElement
virtual void mouseDoubleClickEvent (QMouseEvent *event)
This event is called, if the mouse is double-clicked inside the outer rect of this layout element.
virtual void parentPlotInitialized (QCustomPlot *parentPlot)
Protected Member Functions inherited from QCPLayerable
virtual QCP::Interaction selectionCategory () const
virtual QRect clipRect () const
virtual void selectEvent (QMouseEvent *event, bool additive, const QVariant &details, bool *selectionStateChanged)
virtual void deselectEvent (bool *selectionStateChanged)
void initializeParentPlot (QCustomPlot *parentPlot)
void setParentLayerable (QCPLayerable *parentLayerable)
bool moveToLayer (QCPLayer *layer, bool prepend)
void applyAntialiasingHint (QCPPainter *painter, bool localAntialiased, QCP::AntialiasedElement overrideElement) const
Protected Attributes
QCPColorScale * mParentColorScale
QImage mGradientImage
bool mGradientImageInvalidated
Protected Attributes inherited from QCPAxisRect
QBrush mBackgroundBrush
QPixmap mBackgroundPixmap
QPixmap mScaledBackgroundPixmap
bool mBackgroundScaled
Qt::AspectRatioMode mBackgroundScaledMode
QCPLayoutInset * mInsetLayout
Qt::Orientations mRangeDrag
Qt::Orientations mRangeZoom
QPointer< QCPAxis > mRangeDragHorzAxis
QPointer< QCPAxis > mRangeDragVertAxis
QPointer< QCPAxis > mRangeZoomHorzAxis
QPointer< QCPAxis > mRangeZoomVertAxis
double mRangeZoomFactorHorz
double mRangeZoomFactorVert
QCPRange mDragStartHorzRange
QCPRange mDragStartVertRange
QCP::AntialiasedElements mAADragBackup
QCP::AntialiasedElements mNotAADragBackup
QPoint mDragStart
bool mDragging
QHash< QCPAxis::AxisType,
QList< QCPAxis * > > mAxes
Protected Attributes inherited from QCPLayoutElement
QCPLayout * mParentLayout
QSize mMinimumSize
QSize mMaximumSize
QRect mRect
QRect mOuterRect
QMargins mMargins
QMargins mMinimumMargins
QCP::MarginSides mAutoMargins
QHash< QCP::MarginSide,
QCPMarginGroup * > mMarginGroups
Protected Attributes inherited from QCPLayerable
bool mVisible
QCustomPlot * mParentPlot
QPointer< QCPLayerable > mParentLayerable
QCPLayer * mLayer
bool mAntialiased
Friends
class QCPColorScale
Additional Inherited Members
Public Types inherited from QCPLayoutElement
enum UpdatePhase { upPreparation, upMargins, upLayout }
Defines the phases of the update process, that happens just before a replot.
Signals inherited from QCPLayerable
void layerChanged (QCPLayer *newLayer)
This signal is emitted when the layer of this layerable changes, i.e.
Detailed Description
Definition at line 2362 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPColorScaleAxisRectPrivate::QCPColorScaleAxisRectPrivate (QCPColorScale * parentColorScale) explicit
Creates a new instance, as a child of parentColorScale.
Definition at line 14250 of file qcustomplot.cpp.
References QCPAxis::atBottom, QCPAxis::atLeft, QCPAxis::atRight, QCPAxis::atTop, QCPAxisRect::axis(), axisSelectableChanged(), axisSelectionChanged(), QCPAxis::grid(), QCPLayerable::layerChanged(), QCPLayerable::setLayer(), QCPLayoutElement::setMinimumMargins(), QCPAxis::setPadding(), QCPLayerable::setParentLayerable(), and QCPLayerable::setVisible().
Member Function Documentation
void QCPColorScaleAxisRectPrivate::axisSelectableChanged (QCPAxis::SelectableParts selectableParts) protected
Definition at line 14374 of file qcustomplot.cpp.
References QCPAxis::atBottom, QCPAxis::atLeft, QCPAxis::atRight, QCPAxis::atTop, QCPAxisRect::axis(), QCPAxis::selectableParts(), QCPAxis::setSelectableParts(), and QCPAxis::spAxis.
Referenced by QCPColorScaleAxisRectPrivate().
void QCPColorScaleAxisRectPrivate::axisSelectionChanged (QCPAxis::SelectableParts selectedParts) protected
Definition at line 14350 of file qcustomplot.cpp.
References QCPAxis::atBottom, QCPAxis::atLeft, QCPAxis::atRight, QCPAxis::atTop, QCPAxisRect::axis(), QCPAxis::selectableParts(), QCPAxis::setSelectedParts(), and QCPAxis::spAxis.
Referenced by QCPColorScaleAxisRectPrivate().
void QCPColorScaleAxisRectPrivate::draw (QCPPainter * painter) protected virtual
Reimplemented from QCPAxisRect.
Definition at line 14286 of file qcustomplot.cpp.
References QCPAxis::atBottom, QCPAxis::atLeft, QCPAxis::atRight, QCPAxis::atTop, QCPAxisRect::draw(), QCPColorScale::mColorAxis, mGradientImage, mGradientImageInvalidated, mParentColorScale, QCPLayoutElement::rect(), QCPColorScale::type(), and updateGradientImage().
void QCPColorScaleAxisRectPrivate::updateGradientImage () protected
Definition at line 14308 of file qcustomplot.cpp.
References QCPAxis::atBottom, QCPAxis::atTop, QCPColorGradient::color(), QCPColorGradient::colorize(), QCPColorGradient::levelCount(), QCPColorScale::mGradient, mGradientImage, mGradientImageInvalidated, mParentColorScale, QCPColorScale::mType, and QCPLayoutElement::rect().
Referenced by draw().
Friends And Related Function Documentation
friend class QCPColorScale friend
Definition at line 2382 of file qcustomplot.h.
Member Data Documentation
QImage QCPColorScaleAxisRectPrivate::mGradientImage protected
Definition at line 2369 of file qcustomplot.h.
Referenced by draw(), and updateGradientImage().
bool QCPColorScaleAxisRectPrivate::mGradientImageInvalidated protected
Definition at line 2370 of file qcustomplot.h.
Referenced by draw(), and updateGradientImage().
QCPColorScale* QCPColorScaleAxisRectPrivate::mParentColorScale protected
Definition at line 2368 of file qcustomplot.h.
Referenced by draw(), and updateGradientImage().
The documentation for this class was generated from the following files:
src/qcustomplot.h
src/qcustomplot.cpp