CheckImgLinearity: MunsellColor Class Reference
MunsellColor Class Reference
http://en.wikipedia.org/wiki/Munsell_color_system
#include <MunsellColor.h>
Classes
class Private
Public Member Functions
MunsellColor (QString hue, float val, float chroma)
MunsellColor (QString formatedStr)
MunsellColor ()
virtual ~MunsellColor ()
void setFromString (QString formatedStr)
format: '<Hue> <LightnessVal>/<Chroma>' example:'N 2.75/'
void set (const QString &hue, const float &val, const float &chroma)
void setHue (const QString &hue)
void setLightnessVal (const float &val)
void setChroma (const float &chroma)
QString getHue () const
float getLightnessVal () const
float getChroma () const
QString getFormatedString () const
bool operator== (const MunsellColor &munColor) const
Private Attributes
Private * d
Friends
std::ostream & operator<< (std::ostream &stream, const MunsellColor &munColor)
Detailed Description
http://en.wikipedia.org/wiki/Munsell_color_system
Definition at line 7 of file MunsellColor.h.
Constructor & Destructor Documentation
MunsellColor::MunsellColor (QString hue, float val, float chroma)
Definition at line 19 of file MunsellColor.cpp.
References d, MunsellColor::Private::mChroma, MunsellColor::Private::mHue, and MunsellColor::Private::mLightnessVal.
MunsellColor::MunsellColor (QString formatedStr)
Definition at line 27 of file MunsellColor.cpp.
References setFromString().
MunsellColor::MunsellColor ()
Definition at line 33 of file MunsellColor.cpp.
MunsellColor::~MunsellColor () virtual
Definition at line 36 of file MunsellColor.cpp.
References d.
Member Function Documentation
float MunsellColor::getChroma () const
Definition at line 74 of file MunsellColor.cpp.
References d, and MunsellColor::Private::mChroma.
Referenced by operator==().
QString MunsellColor::getFormatedString () const
Definition at line 75 of file MunsellColor.cpp.
References d, MunsellColor::Private::mChroma, MunsellColor::Private::mHue, and MunsellColor::Private::mLightnessVal.
Referenced by operator<<().
QString MunsellColor::getHue () const
Definition at line 72 of file MunsellColor.cpp.
References d, and MunsellColor::Private::mHue.
Referenced by operator==().
float MunsellColor::getLightnessVal () const
Definition at line 73 of file MunsellColor.cpp.
References d, and MunsellColor::Private::mLightnessVal.
Referenced by operator==().
bool MunsellColor::operator== (const MunsellColor & munColor) const
Definition at line 82 of file MunsellColor.cpp.
References d, getChroma(), getHue(), getLightnessVal(), MunsellColor::Private::mChroma, MunsellColor::Private::mHue, and MunsellColor::Private::mLightnessVal.
void MunsellColor::set (const QString & hue, const float & val, const float & chroma)
Definition at line 43 of file MunsellColor.cpp.
References d, MunsellColor::Private::mChroma, MunsellColor::Private::mHue, and MunsellColor::Private::mLightnessVal.
Referenced by setFromString().
void MunsellColor::setChroma (const float & chroma)
Definition at line 71 of file MunsellColor.cpp.
References d, and MunsellColor::Private::mChroma.
void MunsellColor::setFromString (QString formatedStr)
format: '<Hue> <LightnessVal>/<Chroma>' example:'N 2.75/'
'<Hue> <LightnessVal>/<Chroma>'example : 'N 2.75/'
Definition at line 51 of file MunsellColor.cpp.
References d, FILE_LINE_FUNC_STR, MunsellColor::Private::mChroma, MunsellColor::Private::mHue, MunsellColor::Private::mLightnessVal, and set().
Referenced by MunsellColor().
void MunsellColor::setHue (const QString & hue)
Definition at line 69 of file MunsellColor.cpp.
References d, and MunsellColor::Private::mHue.
void MunsellColor::setLightnessVal (const float & val)
Definition at line 70 of file MunsellColor.cpp.
References d, and MunsellColor::Private::mLightnessVal.
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & stream, const MunsellColor & munColor) friend
Definition at line 92 of file MunsellColor.cpp.
Member Data Documentation
Private* MunsellColor::d private
Definition at line 35 of file MunsellColor.h.
Referenced by getChroma(), getFormatedString(), getHue(), getLightnessVal(), MunsellColor(), operator==(), set(), setChroma(), setFromString(), setHue(), setLightnessVal(), and ~MunsellColor().
The documentation for this class was generated from the following files:
src/MunsellColor.h
src/MunsellColor.cpp