CheckImgLinearity: MainWindow Class Reference
MainWindow Class Reference
#include <mainwindow.h>
Public Member Functions
MainWindow (QWidget *parent=0)
~MainWindow ()
virtual void keyPressEvent (QKeyEvent *event)
void setupDemo (int demoIndex)
void setupQuadraticDemo (QCustomPlot *customPlot)
void setupSimpleDemo (QCustomPlot *customPlot)
void setupSincScatterDemo (QCustomPlot *customPlot)
void setupScatterStyleDemo (QCustomPlot *customPlot)
void setupLineStyleDemo (QCustomPlot *customPlot)
void setupScatterPixmapDemo (QCustomPlot *customPlot)
void setupDateDemo (QCustomPlot *customPlot)
void setupTextureBrushDemo (QCustomPlot *customPlot)
void setupMultiAxisDemo (QCustomPlot *customPlot)
void setupLogarithmicDemo (QCustomPlot *customPlot)
void setupRealtimeDataDemo (QCustomPlot *customPlot)
void setupParametricCurveDemo (QCustomPlot *customPlot)
void setupBarChartDemo (QCustomPlot *customPlot)
void setupStatisticalDemo (QCustomPlot *customPlot)
void setupSimpleItemDemo (QCustomPlot *customPlot)
void setupItemDemo (QCustomPlot *customPlot)
void setupStyledDemo (QCustomPlot *customPlot)
void setupAdvancedAxesDemo (QCustomPlot *customPlot)
void setupColorMapDemo (QCustomPlot *customPlot)
void setupFinancialDemo (QCustomPlot *customPlot)
void setupPlayground (QCustomPlot *customPlot)
Private Slots
void realtimeDataSlot ()
void bracketDataSlot ()
void screenShot ()
void allScreenShots ()
Private Attributes
Ui::MainWindow * ui
QString demoName
QTimer dataTimer
QCPItemTracer * itemDemoPhaseTracer
int currentDemoIndex
Detailed Description
Definition at line 53 of file mainwindow.h.
Constructor & Destructor Documentation
MainWindow::MainWindow (QWidget * parent = 0) explicit
Definition at line 51 of file mainwindow.cpp.
References setupDemo(), and ui.
MainWindow::~MainWindow ()
Definition at line 1598 of file mainwindow.cpp.
References ui.
Member Function Documentation
void MainWindow::allScreenShots () private slot
Definition at line 1616 of file mainwindow.cpp.
References currentDemoIndex, dataTimer, demoName, setupDemo(), and ui.
void MainWindow::bracketDataSlot () private slot
Definition at line 1552 of file mainwindow.cpp.
References itemDemoPhaseTracer, QCPItemTracer::setGraphKey(), and ui.
Referenced by setupItemDemo().
void MainWindow::keyPressEvent (QKeyEvent * event) virtual
Definition at line 88 of file mainwindow.cpp.
References setupDemo().
void MainWindow::realtimeDataSlot () private slot
Definition at line 1503 of file mainwindow.cpp.
References ui.
Referenced by setupRealtimeDataDemo().
void MainWindow::screenShot () private slot
Definition at line 1603 of file mainwindow.cpp.
References demoName.
void MainWindow::setupAdvancedAxesDemo (QCustomPlot * customPlot)
Definition at line 1244 of file mainwindow.cpp.
References QCPAxisRect::addAxes(), QCPAxisRect::addAxis(), QCPLayoutGrid::addElement(), QCustomPlot::addGraph(), QCustomPlot::addPlottable(), QCPAxis::atBottom, QCPAxis::atLeft, QCPAxis::atRight, QCPAxisRect::axes(), QCPAxisRect::axis(), QCustomPlot::axisRects(), QCPLayout::clear(), demoName, QCPAxis::grid(), QCPAbstractPlottable::keyAxis(), QCPGraph::lsImpulse, QCP::msLeft, QCP::msRight, QCustomPlot::plotLayout(), QCPAbstractPlottable::rescaleAxes(), QCPGraph::rescaleAxes(), QCPLayerable::setAntialiased(), QCPAbstractPlottable::setAntialiasedFill(), QCPAxis::setAutoTickCount(), QCPAxis::setAutoTicks(), QCPAbstractPlottable::setBrush(), QCPGraph::setChannelFillGraph(), QCPGraph::setData(), QCPBars::setData(), QCPLayerable::setLayer(), QCPGraph::setLineStyle(), QCPLayoutElement::setMarginGroup(), QCPLayoutElement::setMaximumSize(), QCPLayoutElement::setMinimumSize(), QCPAbstractPlottable::setPen(), QCPAxis::setRangeLower(), QCPGraph::setScatterStyle(), QCPAxis::setSubTickCount(), QCPAxis::setTickLabelColor(), QCPAxis::setTickLabels(), QCPAxis::setTickVector(), QCPAxisRect::setupFullAxesBox(), QCPLayerable::setVisible(), QCPBars::setWidth(), and QCPScatterStyle::ssCircle.
Referenced by setupDemo().
void MainWindow::setupBarChartDemo (QCustomPlot * customPlot)
Definition at line 854 of file mainwindow.cpp.
References QCustomPlot::addPlottable(), QCustomPlot::axisRect(), demoName, QCPAxis::grid(), QCPAxisRect::insetLayout(), QCP::iRangeDrag, QCP::iRangeZoom, QCustomPlot::legend, QCPBars::moveAbove(), QCPAxis::setAutoTickLabels(), QCPAxis::setAutoTicks(), QCPLegend::setBorderPen(), QCPAbstractPlottable::setBrush(), QCPLegend::setBrush(), QCPBars::setData(), QCPLegend::setFont(), QCPLayoutInset::setInsetAlignment(), QCustomPlot::setInteractions(), QCPAxis::setLabel(), QCPAbstractPlottable::setName(), QCPAxis::setPadding(), QCPGrid::setPen(), QCPAbstractPlottable::setPen(), QCPAxis::setRange(), QCPGrid::setSubGridPen(), QCPGrid::setSubGridVisible(), QCPAxis::setSubTickCount(), QCPAxis::setTickLabelRotation(), QCPAxis::setTickLength(), QCPAxis::setTickVector(), QCPAxis::setTickVectorLabels(), QCPLayerable::setVisible(), QCustomPlot::xAxis, and QCustomPlot::yAxis.
Referenced by setupDemo().
void MainWindow::setupColorMapDemo (QCustomPlot * customPlot)
Definition at line 1348 of file mainwindow.cpp.
References QCPLayoutGrid::addElement(), QCustomPlot::addPlottable(), QCPAxis::atRight, QCPColorScale::axis(), QCustomPlot::axisRect(), QCPColorMapData::cellToCoord(), QCPColorMap::data(), demoName, QCPColorGradient::gpPolar, QCP::iRangeDrag, QCP::iRangeZoom, QCP::msBottom, QCP::msTop, QCustomPlot::plotLayout(), QCustomPlot::rescaleAxes(), QCPColorMap::rescaleDataRange(), QCPColorMapData::setCell(), QCPColorMap::setColorScale(), QCPColorMap::setGradient(), QCustomPlot::setInteractions(), QCPAxis::setLabel(), QCPLayoutElement::setMarginGroup(), QCPColorMapData::setRange(), QCPColorMapData::setSize(), QCPColorScale::setType(), QCPAxisRect::setupFullAxesBox(), QCustomPlot::xAxis, and QCustomPlot::yAxis.
Referenced by setupDemo().
void MainWindow::setupDateDemo (QCustomPlot * customPlot)
Definition at line 450 of file mainwindow.cpp.
References QCustomPlot::addGraph(), demoName, QCustomPlot::graph(), QCustomPlot::legend, QCPGraph::lsLine, QCPAxis::ltDateTime, QCPAxis::setAutoTickLabels(), QCPAxis::setAutoTicks(), QCPAxis::setAutoTickStep(), QCPAbstractPlottable::setBrush(), QCPGraph::setData(), QCPAxis::setDateTimeFormat(), QCPAxis::setLabel(), QCPGraph::setLineStyle(), QCPAbstractPlottable::setPen(), QCPAxis::setRange(), QCPAxis::setSubTickCount(), QCPAxis::setTickLabelFont(), QCPAxis::setTickLabels(), QCPAxis::setTickLabelType(), QCPAxis::setTicks(), QCPAxis::setTickStep(), QCPAxis::setTickVector(), QCPAxis::setTickVectorLabels(), QCPLayerable::setVisible(), QCustomPlot::xAxis, QCustomPlot::xAxis2, QCustomPlot::yAxis, and QCustomPlot::yAxis2.
Referenced by setupDemo().
void MainWindow::setupDemo (int demoIndex)
Definition at line 130 of file mainwindow.cpp.
References currentDemoIndex, demoName, setupAdvancedAxesDemo(), setupBarChartDemo(), setupColorMapDemo(), setupDateDemo(), setupFinancialDemo(), setupItemDemo(), setupLineStyleDemo(), setupLogarithmicDemo(), setupMultiAxisDemo(), setupParametricCurveDemo(), setupQuadraticDemo(), setupRealtimeDataDemo(), setupScatterPixmapDemo(), setupScatterStyleDemo(), setupSimpleDemo(), setupSimpleItemDemo(), setupSincScatterDemo(), setupStatisticalDemo(), setupStyledDemo(), setupTextureBrushDemo(), and ui.
Referenced by allScreenShots(), keyPressEvent(), and MainWindow().
void MainWindow::setupFinancialDemo (QCustomPlot * customPlot)
Definition at line 1402 of file mainwindow.cpp.
References QCPLayoutGrid::addElement(), QCustomPlot::addPlottable(), QCPAxis::atBottom, QCPAxis::atLeft, QCPAxisRect::axis(), QCustomPlot::axisRect(), QCPRange::center(), QCPFinancial::csCandlestick, QCPFinancial::csOhlc, demoName, QCPAxis::grid(), QCustomPlot::legend, QCPAxis::ltDateTime, QCP::msBottom, QCP::msLeft, QCP::msRight, QCustomPlot::plotLayout(), QCPAxis::range(), QCustomPlot::rescaleAxes(), QCPAxis::scaleRange(), QCustomPlot::setAutoAddPlottableToLegend(), QCPLayoutElement::setAutoMargins(), QCPAxis::setAutoTickCount(), QCPAxis::setAutoTickStep(), QCPAxis::setBasePen(), QCPAbstractPlottable::setBrush(), QCPFinancial::setBrushNegative(), QCPFinancial::setBrushPositive(), QCPFinancial::setChartStyle(), QCPFinancial::setData(), QCPAxis::setDateTimeFormat(), QCPAxis::setDateTimeSpec(), QCPLayerable::setLayer(), QCPLayoutElement::setMarginGroup(), QCPLayoutElement::setMargins(), QCPLayoutElement::setMaximumSize(), QCPAbstractPlottable::setName(), QCPAbstractPlottable::setPen(), QCPFinancial::setPenNegative(), QCPFinancial::setPenPositive(), QCPLayoutGrid::setRowSpacing(), QCPAxis::setTickLabelRotation(), QCPAxis::setTickLabels(), QCPAxis::setTickLabelType(), QCPAxis::setTicks(), QCPAxis::setTickStep(), QCPFinancial::setTwoColored(), QCPLayerable::setVisible(), QCPBars::setWidth(), QCPFinancial::setWidth(), QCPFinancial::timeSeriesToOhlc(), QCustomPlot::xAxis, and QCustomPlot::yAxis.
Referenced by setupDemo().
void MainWindow::setupItemDemo (QCustomPlot * customPlot)
Definition at line 1011 of file mainwindow.cpp.
References QCustomPlot::addGraph(), QCustomPlot::addItem(), QCPItemText::bottom, bracketDataSlot(), QCPItemBracket::center, dataTimer, demoName, QCPItemCurve::end, QCPItemCurve::endDir, QCPLineEnding::esBar, QCPLineEnding::esSpikeArrow, QCPAxis::grid(), QCP::iRangeDrag, QCP::iRangeZoom, itemDemoPhaseTracer, QCPItemText::left, QCPItemBracket::left, QCPItemAnchor::pixelPoint(), QCPItemText::position, QCPItemTracer::position, QCPItemPosition::ptAxisRectRatio, QCPGraph::rescaleKeyAxis(), QCPItemBracket::right, QCPItemTracer::setBrush(), QCPItemPosition::setCoords(), QCPGraph::setData(), QCPItemText::setFont(), QCPItemTracer::setGraph(), QCPItemTracer::setGraphKey(), QCPItemCurve::setHead(), QCustomPlot::setInteractions(), QCPItemTracer::setInterpolating(), QCPItemBracket::setLength(), QCPItemText::setPadding(), QCPItemPosition::setParentAnchor(), QCPAbstractPlottable::setPen(), QCPItemTracer::setPen(), QCPItemText::setPositionAlignment(), QCPAxis::setRange(), QCPItemText::setRotation(), QCPItemTracer::setSize(), QCPItemTracer::setStyle(), QCPItemCurve::setTail(), QCPItemText::setText(), QCPItemText::setTextAlignment(), QCPItemPosition::setType(), QCPGrid::setZeroLinePen(), QCPItemCurve::start, QCPItemCurve::startDir, QCPItemText::top, QCPItemTracer::tsCircle, QCustomPlot::xAxis, and QCustomPlot::yAxis.
Referenced by setupDemo().
void MainWindow::setupLineStyleDemo (QCustomPlot * customPlot)
Definition at line 363 of file mainwindow.cpp.
References QCustomPlot::addGraph(), QCustomPlot::axisRect(), QCPRange::center(), demoName, QCustomPlot::graph(), QCustomPlot::legend, QCPGraph::lsImpulse, QCPGraph::lsNone, QCPAxis::range(), QCPGraph::rescaleAxes(), QCPAxis::scaleRange(), QCPGraph::setData(), QCPLegend::setFont(), QCPGraph::setLineStyle(), QCPAbstractPlottable::setName(), QCPAbstractPlottable::setPen(), QCPGraph::setScatterStyle(), QCPAxis::setTickLabels(), QCPAxis::setTicks(), QCPAxisRect::setupFullAxesBox(), QCPLayerable::setVisible(), QCPScatterStyle::ssCircle, QCustomPlot::xAxis, and QCustomPlot::yAxis.
Referenced by setupDemo().
void MainWindow::setupLogarithmicDemo (QCustomPlot * customPlot)
Definition at line 679 of file mainwindow.cpp.
References QCustomPlot::addGraph(), QCustomPlot::axisRect(), demoName, QCPGraph::etBoth, QCustomPlot::graph(), QCPAxis::grid(), QCPAxisRect::insetLayout(), QCP::iRangeDrag, QCP::iRangeZoom, QCustomPlot::legend, QCPGraph::lsStepCenter, QCPAbstractPlottable::setBrush(), QCPLegend::setBrush(), QCPGraph::setData(), QCPGraph::setErrorType(), QCPLayoutInset::setInsetAlignment(), QCustomPlot::setInteractions(), QCPGraph::setLineStyle(), QCPAbstractPlottable::setName(), QCustomPlot::setNoAntialiasingOnDrag(), QCPAxis::setNumberFormat(), QCPAxis::setNumberPrecision(), QCPAbstractPlottable::setPen(), QCPAxis::setRange(), QCPAxis::setScaleLogBase(), QCPAxis::setScaleType(), QCPGrid::setSubGridVisible(), QCPAxis::setSubTickCount(), QCPAxisRect::setupFullAxesBox(), QCPLayerable::setVisible(), QCPAxis::stLogarithmic, QCustomPlot::xAxis, QCustomPlot::xAxis2, QCustomPlot::yAxis, and QCustomPlot::yAxis2.
Referenced by setupDemo().
void MainWindow::setupMultiAxisDemo (QCustomPlot * customPlot)
Definition at line 556 of file mainwindow.cpp.
References QCPLayoutGrid::addElement(), QCustomPlot::addGraph(), QCustomPlot::axisRect(), demoName, QCPGraph::etValue, QCustomPlot::graph(), QCPLayoutGrid::insertRow(), QCPAxisRect::insetLayout(), QCP::iRangeDrag, QCP::iRangeZoom, QCustomPlot::legend, QCPGraph::lsLine, QCPGraph::lsNone, QCPGraph::lsStepCenter, QCustomPlot::plotLayout(), QCPAxis::setAutoTickLabels(), QCPAxis::setAutoTicks(), QCPAbstractPlottable::setBrush(), QCPLegend::setBrush(), QCPGraph::setData(), QCPGraph::setDataValueError(), QCPGraph::setErrorType(), QCPLegend::setFont(), QCPLayoutInset::setInsetAlignment(), QCustomPlot::setInteractions(), QCPAxis::setLabel(), QCPGraph::setLineStyle(), QCPAbstractPlottable::setName(), QCPAbstractPlottable::setPen(), QCPAxis::setRange(), QCPGraph::setScatterStyle(), QCPAxis::setSubTickLength(), QCPAxis::setTickLength(), QCPAxis::setTickVector(), QCPAxis::setTickVectorLabels(), QCPLayerable::setVisible(), QCPScatterStyle::ssCircle, QCPScatterStyle::ssDisc, QCustomPlot::xAxis, QCustomPlot::xAxis2, QCustomPlot::yAxis, and QCustomPlot::yAxis2.
Referenced by setupDemo().
void MainWindow::setupParametricCurveDemo (QCustomPlot * customPlot)
Definition at line 806 of file mainwindow.cpp.
References QCustomPlot::addPlottable(), QCustomPlot::axisRect(), demoName, QCP::iRangeDrag, QCP::iRangeZoom, QCP::iSelectPlottables, QCustomPlot::rescaleAxes(), QCPAbstractPlottable::setBrush(), QCPCurve::setData(), QCustomPlot::setInteractions(), QCPAbstractPlottable::setPen(), QCPAxisRect::setupFullAxesBox(), QCustomPlot::xAxis, and QCustomPlot::yAxis.
Referenced by setupDemo().
void MainWindow::setupPlayground (QCustomPlot * customPlot)
Definition at line 1593 of file mainwindow.cpp.
void MainWindow::setupQuadraticDemo (QCustomPlot * customPlot)
Definition at line 162 of file mainwindow.cpp.
References QCustomPlot::addGraph(), demoName, QCustomPlot::graph(), QCPGraph::setData(), QCPAxis::setLabel(), QCPAxis::setRange(), QCustomPlot::xAxis, and QCustomPlot::yAxis.
Referenced by setupDemo().
void MainWindow::setupRealtimeDataDemo (QCustomPlot * customPlot)
Definition at line 758 of file mainwindow.cpp.
References QCustomPlot::addGraph(), QCustomPlot::axisRect(), dataTimer, demoName, QCustomPlot::graph(), QCPGraph::lsNone, QCPAxis::ltDateTime, realtimeDataSlot(), QCPAbstractPlottable::setAntialiasedFill(), QCPAxis::setAutoTickStep(), QCPAbstractPlottable::setBrush(), QCPGraph::setChannelFillGraph(), QCPAxis::setDateTimeFormat(), QCPGraph::setLineStyle(), QCPAbstractPlottable::setPen(), QCPGraph::setScatterStyle(), QCPAxis::setTickLabelType(), QCPAxis::setTickStep(), QCPAxisRect::setupFullAxesBox(), QCPScatterStyle::ssDisc, QCustomPlot::xAxis, QCustomPlot::xAxis2, QCustomPlot::yAxis, and QCustomPlot::yAxis2.
Referenced by setupDemo().
void MainWindow::setupScatterPixmapDemo (QCustomPlot * customPlot)
Definition at line 403 of file mainwindow.cpp.
References QCPLayoutGrid::addElement(), QCustomPlot::addGraph(), QCustomPlot::axisRect(), demoName, QCustomPlot::graph(), QCPLayoutGrid::insertRow(), QCustomPlot::legend, QCPGraph::lsLine, QCustomPlot::plotLayout(), QCPAxis::setAutoTickStep(), QCPAxisRect::setBackground(), QCPAbstractPlottable::setBrush(), QCPGraph::setData(), QCPLegend::setFont(), QCPLegend::setIconSize(), QCPAxis::setLabel(), QCPGraph::setLineStyle(), QCPAbstractPlottable::setName(), QCPAbstractPlottable::setPen(), QCPAxis::setRange(), QCPGraph::setScatterStyle(), QCPAxis::setSubTickCount(), QCPAxis::setTickLabels(), QCPAxis::setTicks(), QCPAxis::setTickStep(), QCPLayerable::setVisible(), QCustomPlot::xAxis, QCustomPlot::xAxis2, QCustomPlot::yAxis, and QCustomPlot::yAxis2.
Referenced by setupDemo().
void MainWindow::setupScatterStyleDemo (QCustomPlot * customPlot)
Definition at line 299 of file mainwindow.cpp.
References QCustomPlot::addGraph(), QCustomPlot::axisRect(), demoName, QCustomPlot::graph(), QCustomPlot::legend, QCPGraph::lsLine, QCustomPlot::rescaleAxes(), QCPGraph::rescaleAxes(), QCPGraph::setData(), QCPLegend::setFont(), QCPGraph::setLineStyle(), QCPAbstractPlottable::setName(), QCPAbstractPlottable::setPen(), QCPLayoutGrid::setRowSpacing(), QCPGraph::setScatterStyle(), QCPAxis::setTickLabels(), QCPAxis::setTicks(), QCPAxisRect::setupFullAxesBox(), QCPLayerable::setVisible(), QCPScatterStyle::ssCircle, QCPScatterStyle::ssCross, QCPScatterStyle::ssCrossCircle, QCPScatterStyle::ssCrossSquare, QCPScatterStyle::ssCustom, QCPScatterStyle::ssDiamond, QCPScatterStyle::ssDisc, QCPScatterStyle::ssPeace, QCPScatterStyle::ssPlus, QCPScatterStyle::ssPlusCircle, QCPScatterStyle::ssPlusSquare, QCPScatterStyle::ssSquare, QCPScatterStyle::ssStar, QCPScatterStyle::ssTriangle, QCPScatterStyle::ssTriangleInverted, QCustomPlot::xAxis, and QCustomPlot::yAxis.
Referenced by setupDemo().
void MainWindow::setupSimpleDemo (QCustomPlot * customPlot)
Definition at line 183 of file mainwindow.cpp.
References QCustomPlot::addGraph(), demoName, QCustomPlot::graph(), QCP::iRangeDrag, QCP::iRangeZoom, QCP::iSelectPlottables, QCPGraph::rescaleAxes(), QCPAbstractPlottable::setBrush(), QCPGraph::setData(), QCustomPlot::setInteractions(), QCPAbstractPlottable::setPen(), QCPAxis::setTickLabels(), QCPLayerable::setVisible(), QCustomPlot::xAxis, QCustomPlot::xAxis2, QCustomPlot::yAxis, and QCustomPlot::yAxis2.
Referenced by setupDemo().
void MainWindow::setupSimpleItemDemo (QCustomPlot * customPlot)
Definition at line 988 of file mainwindow.cpp.
References QCustomPlot::addItem(), QCPItemText::bottom, demoName, QCPItemLine::end, QCPLineEnding::esSpikeArrow, QCP::iRangeDrag, QCP::iRangeZoom, QCPItemText::position, QCPItemPosition::ptAxisRectRatio, QCPItemPosition::setCoords(), QCPItemText::setFont(), QCPItemLine::setHead(), QCustomPlot::setInteractions(), QCPItemPosition::setParentAnchor(), QCPItemText::setPen(), QCPItemText::setPositionAlignment(), QCPItemText::setText(), QCPItemPosition::setType(), and QCPItemLine::start.
Referenced by setupDemo().
void MainWindow::setupSincScatterDemo (QCustomPlot * customPlot)
Definition at line 222 of file mainwindow.cpp.
References QCustomPlot::addGraph(), QCustomPlot::axisRect(), demoName, QCPGraph::etValue, QCustomPlot::graph(), QCPLegend::itemCount(), QCustomPlot::legend, QCPGraph::lsNone, QCPAxis::moveRange(), QCPLegend::removeItem(), QCPGraph::rescaleAxes(), QCPAxis::setAutoTickCount(), QCPAbstractPlottable::setBrush(), QCPGraph::setChannelFillGraph(), QCPGraph::setData(), QCPGraph::setDataValueError(), QCPGraph::setErrorPen(), QCPGraph::setErrorType(), QCPLegend::setFont(), QCPGraph::setLineStyle(), QCPAbstractPlottable::setName(), QCPAxis::setNumberFormat(), QCPAxis::setNumberPrecision(), QCPAbstractPlottable::setPen(), QCPGraph::setScatterStyle(), QCPAxis::setTickLabelRotation(), QCPAxisRect::setupFullAxesBox(), QCPLayerable::setVisible(), QCPScatterStyle::ssCross, and QCustomPlot::xAxis.
Referenced by setupDemo().
void MainWindow::setupStatisticalDemo (QCustomPlot * customPlot)
Definition at line 932 of file mainwindow.cpp.
References QCustomPlot::addPlottable(), QCPRange::center(), demoName, QCP::iRangeDrag, QCP::iRangeZoom, QCPAxis::range(), QCustomPlot::rescaleAxes(), QCPAxis::scaleRange(), QCPAxis::setAutoTickLabels(), QCPAxis::setAutoTicks(), QCPAbstractPlottable::setBrush(), QCustomPlot::setInteractions(), QCPStatisticalBox::setKey(), QCPAxis::setLabel(), QCPStatisticalBox::setLowerQuartile(), QCPStatisticalBox::setMaximum(), QCPStatisticalBox::setMedian(), QCPStatisticalBox::setMinimum(), QCPStatisticalBox::setOutliers(), QCPAxis::setRange(), QCPAxis::setSubTickCount(), QCPAxis::setTickLabelRotation(), QCPAxis::setTickLength(), QCPAxis::setTickVector(), QCPAxis::setTickVectorLabels(), QCPStatisticalBox::setUpperQuartile(), QCustomPlot::xAxis, and QCustomPlot::yAxis.
Referenced by setupDemo().
void MainWindow::setupStyledDemo (QCustomPlot * customPlot)
Definition at line 1144 of file mainwindow.cpp.
References QCustomPlot::addGraph(), QCustomPlot::addLayer(), QCustomPlot::addPlottable(), QCustomPlot::axisRect(), demoName, QCPLineEnding::esSpikeArrow, QCPAxis::grid(), QCustomPlot::layer(), QCustomPlot::limAbove, QCustomPlot::limBelow, QCPBars::moveAbove(), QCustomPlot::rescaleAxes(), QCustomPlot::setBackground(), QCPAxisRect::setBackground(), QCPAxis::setBasePen(), QCPAbstractPlottable::setBrush(), QCPGraph::setChannelFillGraph(), QCPGraph::setData(), QCPBars::setData(), QCPLayerable::setLayer(), QCPGrid::setPen(), QCPAbstractPlottable::setPen(), QCPAxis::setRange(), QCPGraph::setScatterStyle(), QCPGrid::setSubGridPen(), QCPGrid::setSubGridVisible(), QCPAxis::setSubTickPen(), QCPAxis::setTickLabelColor(), QCPAxis::setTickPen(), QCPAxis::setUpperEnding(), QCPBars::setWidth(), QCPGrid::setZeroLinePen(), QCPScatterStyle::ssCircle, QCustomPlot::xAxis, and QCustomPlot::yAxis.
Referenced by setupDemo().
void MainWindow::setupTextureBrushDemo (QCustomPlot * customPlot)
Definition at line 511 of file mainwindow.cpp.
References QCustomPlot::addGraph(), QCustomPlot::axisRect(), demoName, QCustomPlot::graph(), QCPAbstractPlottable::setBrush(), QCPGraph::setChannelFillGraph(), QCPGraph::setData(), QCPAbstractPlottable::setPen(), QCPAxis::setRange(), QCPAxis::setTickLabels(), QCPAxisRect::setupFullAxesBox(), QCPLayerable::setVisible(), QCustomPlot::xAxis, QCustomPlot::xAxis2, QCustomPlot::yAxis, and QCustomPlot::yAxis2.
Referenced by setupDemo().
Member Data Documentation
int MainWindow::currentDemoIndex private
Definition at line 98 of file mainwindow.h.
Referenced by allScreenShots(), and setupDemo().
QTimer MainWindow::dataTimer private
Definition at line 96 of file mainwindow.h.
Referenced by allScreenShots(), setupItemDemo(), and setupRealtimeDataDemo().
QString MainWindow::demoName private
Definition at line 95 of file mainwindow.h.
Referenced by allScreenShots(), screenShot(), setupAdvancedAxesDemo(), setupBarChartDemo(), setupColorMapDemo(), setupDateDemo(), setupDemo(), setupFinancialDemo(), setupItemDemo(), setupLineStyleDemo(), setupLogarithmicDemo(), setupMultiAxisDemo(), setupParametricCurveDemo(), setupQuadraticDemo(), setupRealtimeDataDemo(), setupScatterPixmapDemo(), setupScatterStyleDemo(), setupSimpleDemo(), setupSimpleItemDemo(), setupSincScatterDemo(), setupStatisticalDemo(), setupStyledDemo(), and setupTextureBrushDemo().
QCPItemTracer* MainWindow::itemDemoPhaseTracer private
Definition at line 97 of file mainwindow.h.
Referenced by bracketDataSlot(), and setupItemDemo().
Ui::MainWindow* MainWindow::ui private
Definition at line 94 of file mainwindow.h.
Referenced by allScreenShots(), bracketDataSlot(), MainWindow(), realtimeDataSlot(), setupDemo(), and ~MainWindow().
The documentation for this class was generated from the following files:
src/mainwindow.h
src/mainwindow.cpp