CheckImgLinearity: ImagePlugin Class Reference
ImagePlugin Class Reference abstract
#include <ImagePlugin.h>
Public Types
typedef std::pair< int, int > pixelCoord
typedef std::vector< pixelCoord > pixelsCoords
Public Member Functions
bool withColorSpaceHandler ()
QString colorSpace ()
bool toColorSpace (QString colorSpaceName)
virtual QString getImageFilterExtensions ()=0
Use as filter menu on Open (example: 'Image (*.png *.jpg *.bmp)')
virtual bool loadImage (QString filename)=0
Load the image in memory for next use.
virtual QImage toQImage ()=0
Get a conversion to a QImage (allow to show something into the GUI)
virtual QSize size ()=0
Get the image resolution.
virtual float readSinglePixelChannel (int x, int y, int channel)=0
virtual bool averagesChannels (pixelsCoords pixCoords, float &r, float &g, float &b, float &a)=0
Get the averages pixel channels given a list of pixel coord x,y.
virtual bool save (QString filename)=0
Try to write an output filename from the opened/loaded image (based on the file extension)
Static Public Member Functions
static pixelCoord makePixelCoord (int x, int y)
Protected Member Functions
virtual bool colorSpaceConversion ()
need to be overloaded by subclass supporting colorspace and should use mColorSpace
Protected Attributes
QString mColorSpace
it's up to the sub class to internaly activate this option
Detailed Description
Definition at line 9 of file ImagePlugin.h.
Member Typedef Documentation
typedef std::pair<int,int> ImagePlugin::pixelCoord
Definition at line 16 of file ImagePlugin.h.
typedef std::vector<pixelCoord> ImagePlugin::pixelsCoords
Definition at line 17 of file ImagePlugin.h.
Member Function Documentation
virtual bool ImagePlugin::averagesChannels (pixelsCoords pixCoords, float & r, float & g, float & b, float & a) pure virtual
Get the averages pixel channels given a list of pixel coord x,y.
Implemented in ImagePluginOIIO, and ImagePluginQt.
Referenced by ColorSwatchPatch::computeAverageRGBpixel().
QString ImagePlugin::colorSpace () inline
Definition at line 22 of file ImagePlugin.h.
References mColorSpace.
virtual bool ImagePlugin::colorSpaceConversion () inline protected virtual
need to be overloaded by subclass supporting colorspace and should use mColorSpace
Reimplemented in ImagePluginOIIO.
Definition at line 27 of file ImagePlugin.h.
Referenced by toColorSpace().
virtual QString ImagePlugin::getImageFilterExtensions () pure virtual
Use as filter menu on Open (example: 'Image (*.png *.jpg *.bmp)')
Implemented in ImagePluginOIIO, and ImagePluginQt.
virtual bool ImagePlugin::loadImage (QString filename) pure virtual
Load the image in memory for next use.
Implemented in ImagePluginOIIO, and ImagePluginQt.
Referenced by ColorSwatch::loadImages().
static pixelCoord ImagePlugin::makePixelCoord (int x, int y) inline static
Definition at line 18 of file ImagePlugin.h.
Referenced by ColorSwatchPatch::computeAverageRGBpixel().
virtual float ImagePlugin::readSinglePixelChannel (int x, int y, int channel) pure virtual
Implemented in ImagePluginOIIO, and ImagePluginQt.
Referenced by ColorSwatch::fillPatchesPixelsFromMask().
virtual bool ImagePlugin::save (QString filename) pure virtual
Try to write an output filename from the opened/loaded image (based on the file extension)
Implemented in ImagePluginOIIO, and ImagePluginQt.
virtual QSize ImagePlugin::size () pure virtual
Get the image resolution.
Implemented in ImagePluginOIIO, and ImagePluginQt.
Referenced by ColorSwatch::loadImages().
bool ImagePlugin::toColorSpace (QString colorSpaceName) inline
Definition at line 23 of file ImagePlugin.h.
References colorSpaceConversion().
virtual QImage ImagePlugin::toQImage () pure virtual
Get a conversion to a QImage (allow to show something into the GUI)
Implemented in ImagePluginOIIO, and ImagePluginQt.
Referenced by ColorSwatch::getQImage(), ColorSwatch::haveImage(), and ColorSwatch::loadImages().
bool ImagePlugin::withColorSpaceHandler () inline
Definition at line 21 of file ImagePlugin.h.
Member Data Documentation
QString ImagePlugin::mColorSpace protected
it's up to the sub class to internaly activate this option
Definition at line 13 of file ImagePlugin.h.
Referenced by colorSpace(), ImagePluginOIIO::colorSpaceConversion(), and ImagePluginOIIO::ImagePluginOIIO().
The documentation for this class was generated from the following file:
src/ImagePlugin.h