CheckImgLinearity: QCPRange Class Reference
QCPRange Class Reference
Represents the range an axis is encompassing.
#include <qcustomplot.h>
Public Member Functions
QCPRange ()
Constructs a range with lower and upper set to zero.
QCPRange (double lower, double upper)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Constructs a range with the specified lower and upper values.
bool operator== (const QCPRange &other) const
bool operator!= (const QCPRange &other) const
QCPRange & operator+= (const double &value)
Adds value to both boundaries of the range.
QCPRange & operator-= (const double &value)
Subtracts value from both boundaries of the range.
QCPRange & operator*= (const double &value)
Multiplies both boundaries of the range by value.
QCPRange & operator/= (const double &value)
Divides both boundaries of the range by value.
double size () const
Returns the size of the range, i.e.
double center () const
Returns the center of the range, i.e.
void normalize ()
Makes sure lower is numerically smaller than upper.
void expand (const QCPRange &otherRange)
Expands this range such that otherRange is contained in the new range.
QCPRange expanded (const QCPRange &otherRange) const
Returns an expanded range that contains this and otherRange.
QCPRange sanitizedForLogScale () const
Returns a sanitized version of the range.
QCPRange sanitizedForLinScale () const
Returns a sanitized version of the range.
bool contains (double value) const
Returns true when value lies within or exactly on the borders of the range.
Static Public Member Functions
static bool validRange (double lower, double upper)
Checks, whether the specified range is within valid bounds, which are defined as QCPRange::maxRange and QCPRange::minRange.
static bool validRange (const QCPRange &range)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Checks, whether the specified range is within valid bounds, which are defined as QCPRange::maxRange and QCPRange::minRange.
Public Attributes
double lower
double upper
Static Public Attributes
static const double minRange = 1e-280
Minimum range size (upper - lower) the range changing functions will accept.
static const double maxRange = 1e250
Maximum values (negative and positive) the range will accept in range-changing functions.
Friends
const QCPRange operator+ (const QCPRange &, double)
Adds value to both boundaries of the range.
const QCPRange operator+ (double, const QCPRange &)
Adds value to both boundaries of the range.
const QCPRange operator- (const QCPRange &range, double value)
Subtracts value from both boundaries of the range.
const QCPRange operator* (const QCPRange &range, double value)
Multiplies both boundaries of the range by value.
const QCPRange operator* (double value, const QCPRange &range)
Multiplies both boundaries of the range by value.
const QCPRange operator/ (const QCPRange &range, double value)
Divides both boundaries of the range by value.
Detailed Description
Represents the range an axis is encompassing.
contains a lower and upper double value and provides convenience input, output and modification functions.
See also
QCPAxis::setRange
Definition at line 476 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPRange::QCPRange ()
Constructs a range with lower and upper set to zero.
Definition at line 1309 of file qcustomplot.cpp.
QCPRange::QCPRange (double lower, double upper)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Constructs a range with the specified lower and upper values.
Definition at line 1318 of file qcustomplot.cpp.
References normalize().
Member Function Documentation
double QCPRange::center () const
Returns the center of the range, i.e.
(upper+lower)*0.5
Definition at line 1336 of file qcustomplot.cpp.
References lower, and upper.
Referenced by MainWindow::setupFinancialDemo(), MainWindow::setupLineStyleDemo(), and MainWindow::setupStatisticalDemo().
bool QCPRange::contains (double value) const
Returns true when value lies within or exactly on the borders of the range.
Definition at line 1452 of file qcustomplot.cpp.
References lower, and upper.
Referenced by QCPFinancial::candlestickSelectTest(), QCPStatisticalBox::selectTest(), and QCPColorMap::selectTest().
void QCPRange::expand (const QCPRange & otherRange)
Expands this range such that otherRange is contained in the new range.
It is assumed that both this range and otherRange are normalized (see normalize).
If otherRange is already inside the current range, this function does nothing.
See also
expanded
Definition at line 1359 of file qcustomplot.cpp.
References lower, and upper.
Referenced by expanded(), QCPAxis::rescale(), QCPColorScale::rescaleDataRange(), QCPAbstractPlottable::rescaleKeyAxis(), and QCPAbstractPlottable::rescaleValueAxis().
QCPRange QCPRange::expanded (const QCPRange & otherRange) const
Returns an expanded range that contains this and otherRange.
It is assumed that both this range and otherRange are normalized (see normalize).
See also
expand
Definition at line 1374 of file qcustomplot.cpp.
References expand().
void QCPRange::normalize ()
Makes sure lower is numerically smaller than upper.
If this is not the case, the values are swapped.
Definition at line 1345 of file qcustomplot.cpp.
References lower, and upper.
Referenced by QCPColorMap::getKeyRange(), QCPColorMap::getValueRange(), QCPRange(), sanitizedForLinScale(), and sanitizedForLogScale().
bool QCPRange::operator!= (const QCPRange & other) const inline
Definition at line 485 of file qcustomplot.h.
QCPRange & QCPRange::operator*= (const double & value) inline
Multiplies both boundaries of the range by value.
Definition at line 489 of file qcustomplot.h.
QCPRange & QCPRange::operator+= (const double & value) inline
Adds value to both boundaries of the range.
Definition at line 487 of file qcustomplot.h.
QCPRange & QCPRange::operator-= (const double & value) inline
Subtracts value from both boundaries of the range.
Definition at line 488 of file qcustomplot.h.
QCPRange & QCPRange::operator/= (const double & value) inline
Divides both boundaries of the range by value.
Definition at line 490 of file qcustomplot.h.
bool QCPRange::operator== (const QCPRange & other) const inline
Definition at line 484 of file qcustomplot.h.
References lower, and upper.
QCPRange QCPRange::sanitizedForLinScale () const
Returns a sanitized version of the range.
Sanitized means for linear scales, that lower will always be numerically smaller (or equal) to upper.
Definition at line 1442 of file qcustomplot.cpp.
References lower, normalize(), and upper.
Referenced by QCPAxis::scaleRange(), QCPColorMap::setDataRange(), QCPAxis::setRange(), QCPAxis::setRangeLower(), and QCPAxis::setRangeUpper().
QCPRange QCPRange::sanitizedForLogScale () const
Returns a sanitized version of the range.
Sanitized means for logarithmic scales, that the range won't span the positive and negative sign domain, i.e. contain zero. Further lower will always be numerically smaller (or equal) to upper.
If the original range does span positive and negative sign domains or contains zero, the returned range will try to approximate the original range as good as possible. If the positive interval of the original range is wider than the negative interval, the returned range will only contain the positive interval, with lower bound set to rangeFac or rangeFac *upper, whichever is closer to zero. Same procedure is used if the negative interval is wider than the positive interval, this time by changing the upper bound.
Definition at line 1393 of file qcustomplot.cpp.
References lower, normalize(), and upper.
Referenced by QCPAxis::scaleRange(), QCPColorMap::setDataRange(), QCPColorScale::setDataScaleType(), QCPColorMap::setDataScaleType(), QCPAxis::setRange(), QCPAxis::setRangeLower(), QCPAxis::setRangeUpper(), and QCPAxis::setScaleType().
double QCPRange::size () const
Returns the size of the range, i.e.
upper-lower
Definition at line 1328 of file qcustomplot.cpp.
References lower, and upper.
Referenced by QCPColorGradient::color(), QCPColorGradient::colorize(), QCPAxis::coordToPixel(), QCPColorMap::draw(), QCPGrid::drawGridLines(), QCPAxis::generateAutoTicks(), QCPAxis::pixelToCoord(), QCPAxis::rescale(), QCPColorScale::rescaleDataRange(), QCPAbstractPlottable::rescaleKeyAxis(), QCPAbstractPlottable::rescaleValueAxis(), QCPAxis::setScaleRatio(), and QCPAxis::setupTickVectors().
bool QCPRange::validRange (double lower, double upper) static
Checks, whether the specified range is within valid bounds, which are defined as QCPRange::maxRange and QCPRange::minRange.
A valid range means:
range bounds within -maxRange and maxRange
range size above minRange
range size below maxRange
Definition at line 1465 of file qcustomplot.cpp.
References maxRange, and minRange.
Referenced by QCPAxis::rescale(), QCPColorScale::rescaleDataRange(), QCPAbstractPlottable::rescaleKeyAxis(), QCPAbstractPlottable::rescaleValueAxis(), QCPAxis::scaleRange(), QCPColorMap::setDataRange(), and QCPAxis::setRange().
bool QCPRange::validRange (const QCPRange & range) static
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Checks, whether the specified range is within valid bounds, which are defined as QCPRange::maxRange and QCPRange::minRange.
A valid range means:
range bounds within -maxRange and maxRange
range size above minRange
range size below maxRange
Definition at line 1489 of file qcustomplot.cpp.
References lower, maxRange, minRange, and upper.
Friends And Related Function Documentation
const QCPRange operator* (const QCPRange & range, double value) friend
Multiplies both boundaries of the range by value.
Definition at line 572 of file qcustomplot.h.
const QCPRange operator* (double value, const QCPRange & range) friend
Multiplies both boundaries of the range by value.
Definition at line 582 of file qcustomplot.h.
const QCPRange operator+ (const QCPRange & range, double value) friend
Adds value to both boundaries of the range.
Definition at line 542 of file qcustomplot.h.
const QCPRange operator+ (double value, const QCPRange & range) friend
Adds value to both boundaries of the range.
Definition at line 552 of file qcustomplot.h.
const QCPRange operator- (const QCPRange & range, double value) friend
Subtracts value from both boundaries of the range.
Definition at line 562 of file qcustomplot.h.
const QCPRange operator/ (const QCPRange & range, double value) friend
Divides both boundaries of the range by value.
Definition at line 592 of file qcustomplot.h.
Member Data Documentation
double QCPRange::lower
Definition at line 479 of file qcustomplot.h.
Referenced by QCPColorMapData::cellToCoord(), center(), QCPColorGradient::color(), QCPColorGradient::colorize(), contains(), QCPColorMapData::coordToCell(), QCPAxis::coordToPixel(), QCPColorMapData::data(), QCPColorMap::draw(), QCPGrid::drawGridLines(), expand(), QCPAxis::generateAutoTicks(), QCPCurve::getCurveData(), QCPGraph::getKeyRange(), QCPCurve::getKeyRange(), QCPBars::getKeyRange(), QCPColorMap::getKeyRange(), QCPFinancial::getKeyRange(), QCPGraph::getPreparedData(), QCPGraph::getValueRange(), QCPCurve::getValueRange(), QCPBars::getValueRange(), QCPColorMap::getValueRange(), QCPFinancial::getValueRange(), QCPAxisRect::mouseMoveEvent(), QCPAxis::moveRange(), normalize(), operator==(), QCPAxis::pixelToCoord(), QCPColorMapData::recalculateDataBounds(), QCPAxis::rescale(), QCPColorScale::rescaleDataRange(), QCPAbstractPlottable::rescaleKeyAxis(), QCPGraph::rescaleKeyAxis(), QCPAbstractPlottable::rescaleValueAxis(), QCPGraph::rescaleValueAxis(), sanitizedForLinScale(), sanitizedForLogScale(), QCPAxis::scaleRange(), QCPColorMapData::setCell(), QCPColorMapData::setData(), QCPColorScale::setDataRange(), QCPColorMap::setDataRange(), QCPAxis::setRange(), QCPAxis::setRangeLower(), QCPAxis::setupTickVectors(), size(), validRange(), and QCPAxis::visibleTickBounds().
const double QCPRange::maxRange = 1e250 static
Maximum values (negative and positive) the range will accept in range-changing functions.
Larger absolute values would cause errors due to the 11-bit exponent of double precision numbers, corresponding to a maximum magnitude of roughly 1e308. Since the number of planck-volumes in the entire visible universe is only ~1e183, this should be enough.
See also
validRange, minRange
Definition at line 510 of file qcustomplot.h.
Referenced by validRange().
const double QCPRange::minRange = 1e-280 static
Minimum range size (upper - lower) the range changing functions will accept.
Smaller intervals would cause errors due to the 11-bit exponent of double precision numbers, corresponding to a minimum magnitude of roughly 1e-308.
See also
validRange, maxRange
Definition at line 509 of file qcustomplot.h.
Referenced by validRange().
double QCPRange::upper
Definition at line 479 of file qcustomplot.h.
Referenced by QCPColorMapData::cellToCoord(), center(), QCPColorGradient::color(), QCPColorGradient::colorize(), contains(), QCPColorMapData::coordToCell(), QCPAxis::coordToPixel(), QCPColorMapData::data(), QCPColorMap::draw(), QCPGrid::drawGridLines(), expand(), QCPAxis::generateAutoTicks(), QCPCurve::getCurveData(), QCPGraph::getKeyRange(), QCPCurve::getKeyRange(), QCPBars::getKeyRange(), QCPColorMap::getKeyRange(), QCPFinancial::getKeyRange(), QCPGraph::getPreparedData(), QCPGraph::getValueRange(), QCPCurve::getValueRange(), QCPBars::getValueRange(), QCPColorMap::getValueRange(), QCPFinancial::getValueRange(), QCPGraph::lowerFillBasePoint(), QCPAxisRect::mouseMoveEvent(), QCPAxis::moveRange(), normalize(), operator==(), QCPAxis::pixelToCoord(), QCPColorMapData::recalculateDataBounds(), QCPAxis::rescale(), QCPColorScale::rescaleDataRange(), QCPAbstractPlottable::rescaleKeyAxis(), QCPGraph::rescaleKeyAxis(), QCPAbstractPlottable::rescaleValueAxis(), QCPGraph::rescaleValueAxis(), sanitizedForLinScale(), sanitizedForLogScale(), QCPAxis::scaleRange(), QCPColorMapData::setCell(), QCPColorMapData::setData(), QCPColorScale::setDataRange(), QCPColorMap::setDataRange(), QCPAxis::setRange(), QCPAxis::setRangeUpper(), QCPAxis::setupTickVectors(), size(), QCPGraph::upperFillBasePoint(), validRange(), and QCPAxis::visibleTickBounds().
The documentation for this class was generated from the following files:
src/qcustomplot.h
src/qcustomplot.cpp