CheckImgLinearity: QCPItemCurve Class Reference
QCPItemCurve Class Reference
A curved line from one point to another.
#include <qcustomplot.h>
Public Member Functions
QCPItemCurve (QCustomPlot *parentPlot)
Creates a curve item and sets default values.
virtual ~QCPItemCurve ()
QPen pen () const
QPen selectedPen () const
QCPLineEnding head () const
QCPLineEnding tail () const
void setPen (const QPen &pen)
Sets the pen that will be used to draw the line.
void setSelectedPen (const QPen &pen)
Sets the pen that will be used to draw the line when selected.
void setHead (const QCPLineEnding &head)
Sets the line ending style of the head.
void setTail (const QCPLineEnding &tail)
Sets the line ending style of the tail.
virtual double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const
This function is used to decide whether a click hits a layerable object or not.
Public Member Functions inherited from QCPAbstractItem
QCPAbstractItem (QCustomPlot *parentPlot)
Base class constructor which initializes base class members.
virtual ~QCPAbstractItem ()
bool clipToAxisRect () const
QCPAxisRect * clipAxisRect () const
bool selectable () const
bool selected () const
void setClipToAxisRect (bool clip)
Sets whether the item shall be clipped to an axis rect or whether it shall be visible on the entire QCustomPlot.
void setClipAxisRect (QCPAxisRect *rect)
Sets the clip axis rect.
Q_SLOT void setSelectable (bool selectable)
Sets whether the user can (de-)select this item by clicking on the QCustomPlot surface.
Q_SLOT void setSelected (bool selected)
Sets whether this item is selected or not.
QList< QCPItemPosition * > positions () const
Returns all positions of the item in a list.
QList< QCPItemAnchor * > anchors () const
Returns all anchors of the item in a list.
QCPItemPosition * position (const QString &name) const
Returns the QCPItemPosition with the specified name.
QCPItemAnchor * anchor (const QString &name) const
Returns the QCPItemAnchor with the specified name.
bool hasAnchor (const QString &name) const
Returns whether this item has an anchor with the specified name.
Public Member Functions inherited from QCPLayerable
QCPLayerable (QCustomPlot *plot, QString targetLayer=QString(), QCPLayerable *parentLayerable=0)
Creates a new QCPLayerable instance.
~QCPLayerable ()
bool visible () const
QCustomPlot * parentPlot () const
QCPLayerable * parentLayerable () const
Returns the parent layerable of this layerable.
QCPLayer * layer () const
bool antialiased () const
void setVisible (bool on)
Sets the visibility of this layerable object.
Q_SLOT bool setLayer (QCPLayer *layer)
Sets the layer of this layerable object.
bool setLayer (const QString &layerName)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Sets the layer of this layerable object by name.
void setAntialiased (bool enabled)
Sets whether this object will be drawn antialiased or not.
bool realVisibility () const
Returns whether this layerable is visible, taking the visibility of the layerable parent and the visibility of the layer this layerable is on into account.
Public Attributes
QCPItemPosition *const start
QCPItemPosition *const startDir
QCPItemPosition *const endDir
QCPItemPosition *const end
Protected Member Functions
virtual void draw (QCPPainter *painter)
QPen mainPen () const
Protected Member Functions inherited from QCPAbstractItem
virtual QCP::Interaction selectionCategory () const
virtual QRect clipRect () const
virtual void applyDefaultAntialiasingHint (QCPPainter *painter) const
virtual void selectEvent (QMouseEvent *event, bool additive, const QVariant &details, bool *selectionStateChanged)
virtual void deselectEvent (bool *selectionStateChanged)
virtual QPointF anchorPixelPoint (int anchorId) const
double distSqrToLine (const QPointF &start, const QPointF &end, const QPointF &point) const
double rectSelectTest (const QRectF &rect, const QPointF &pos, bool filledRect) const
QCPItemPosition * createPosition (const QString &name)
QCPItemAnchor * createAnchor (const QString &name, int anchorId)
Protected Member Functions inherited from QCPLayerable
virtual void parentPlotInitialized (QCustomPlot *parentPlot)
void initializeParentPlot (QCustomPlot *parentPlot)
void setParentLayerable (QCPLayerable *parentLayerable)
bool moveToLayer (QCPLayer *layer, bool prepend)
void applyAntialiasingHint (QCPPainter *painter, bool localAntialiased, QCP::AntialiasedElement overrideElement) const
Protected Attributes
QPen mPen
QPen mSelectedPen
QCPLineEnding mHead
QCPLineEnding mTail
Protected Attributes inherited from QCPAbstractItem
bool mClipToAxisRect
QPointer< QCPAxisRect > mClipAxisRect
QList< QCPItemPosition * > mPositions
QList< QCPItemAnchor * > mAnchors
bool mSelectable
bool mSelected
Protected Attributes inherited from QCPLayerable
bool mVisible
QCustomPlot * mParentPlot
QPointer< QCPLayerable > mParentLayerable
QCPLayer * mLayer
bool mAntialiased
Additional Inherited Members
Signals inherited from QCPAbstractItem
void selectionChanged (bool selected)
This signal is emitted when the selection state of this item has changed, either by user interaction or by a direct call to setSelected.
void selectableChanged (bool selectable)
Signals inherited from QCPLayerable
void layerChanged (QCPLayer *newLayer)
This signal is emitted when the layer of this layerable changes, i.e.
Detailed Description
A curved line from one point to another.
Curve example. Blue dotted circles are anchors, solid blue discs are positions.
It has four positions, start and end, which define the end points of the line, and two control points which define the direction the line exits from the start and the direction from which it approaches the end: startDir and endDir.
With setHead and setTail you may set different line ending styles, e.g. to create an arrow.
Often it is desirable for the control points to stay at fixed relative positions to the start/end point. This can be achieved by setting the parent anchor e.g. of startDir simply to start, and then specify the desired pixel offset with QCPItemPosition::setCoords on startDir.
Definition at line 3321 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPItemCurve::QCPItemCurve (QCustomPlot * parentPlot)
Creates a curve item and sets default values.
The constructed item can be added to the plot with QCustomPlot::addItem.
Definition at line 21824 of file qcustomplot.cpp.
References end, endDir, QCPItemPosition::setCoords(), setPen(), setSelectedPen(), start, and startDir.
QCPItemCurve::~QCPItemCurve () virtual
Definition at line 21840 of file qcustomplot.cpp.
Member Function Documentation
void QCPItemCurve::draw (QCPPainter * painter) protected virtual
Implements QCPAbstractItem.
Definition at line 21917 of file qcustomplot.cpp.
References QCPAbstractItem::clipRect(), QCPLineEnding::draw(), end, endDir, QCPLineEnding::esNone, mainPen(), mHead, mTail, QCPItemPosition::pixelPoint(), QCPPainter::setPen(), start, startDir, and QCPLineEnding::style().
QCPLineEnding QCPItemCurve::head () const inline
Definition at line 3337 of file qcustomplot.h.
Referenced by setHead().
QPen QCPItemCurve::mainPen () const protected
Definition at line 21951 of file qcustomplot.cpp.
References mPen, QCPAbstractItem::mSelected, and mSelectedPen.
Referenced by draw().
QPen QCPItemCurve::pen () const inline
Definition at line 3335 of file qcustomplot.h.
Referenced by setPen(), and setSelectedPen().
QPen QCPItemCurve::selectedPen () const inline
Definition at line 3336 of file qcustomplot.h.
double QCPItemCurve::selectTest (const QPointF & pos, bool onlySelectable, QVariant * details = 0) const virtual
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the item is represented not by single lines but by an area like QCPItemRect or QCPItemText, a click inside the area returns a constant value greater zero (typically the selectionTolerance of the parent QCustomPlot multiplied by 0.99). If the click lies outside the area, this function returns -1.0.
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
You may pass 0 as details to indicate that you are not interested in those selection details.
See also
selectEvent, deselectEvent, QCustomPlot::setInteractions
Implements QCPAbstractItem.
Definition at line 21891 of file qcustomplot.cpp.
References QCPAbstractItem::distSqrToLine(), end, endDir, QCPAbstractItem::mSelectable, QCPItemPosition::pixelPoint(), start, and startDir.
void QCPItemCurve::setHead (const QCPLineEnding & head)
Sets the line ending style of the head.
The head corresponds to the end position.
Note that due to the overloaded QCPLineEnding constructor, you may directly specify a QCPLineEnding::EndingStyle here, e.g.
setHead(QCPLineEnding::esSpikeArrow)
See also
setTail
Definition at line 21872 of file qcustomplot.cpp.
References head(), and mHead.
Referenced by MainWindow::setupItemDemo().
void QCPItemCurve::setPen (const QPen & pen)
Sets the pen that will be used to draw the line.
See also
setSelectedPen
Definition at line 21849 of file qcustomplot.cpp.
References mPen, and pen().
Referenced by QCPItemCurve().
void QCPItemCurve::setSelectedPen (const QPen & pen)
Sets the pen that will be used to draw the line when selected.
See also
setPen, setSelected
Definition at line 21859 of file qcustomplot.cpp.
References mSelectedPen, and pen().
Referenced by QCPItemCurve().
void QCPItemCurve::setTail (const QCPLineEnding & tail)
Sets the line ending style of the tail.
The tail corresponds to the start position.
Note that due to the overloaded QCPLineEnding constructor, you may directly specify a QCPLineEnding::EndingStyle here, e.g.
setTail(QCPLineEnding::esSpikeArrow)
See also
setHead
Definition at line 21885 of file qcustomplot.cpp.
References mTail, and tail().
Referenced by MainWindow::setupItemDemo().
QCPLineEnding QCPItemCurve::tail () const inline
Definition at line 3338 of file qcustomplot.h.
Referenced by setTail().
Member Data Documentation
QCPItemPosition* const QCPItemCurve::end
Definition at line 3352 of file qcustomplot.h.
Referenced by draw(), QCPItemCurve(), selectTest(), and MainWindow::setupItemDemo().
QCPItemPosition* const QCPItemCurve::endDir
Definition at line 3351 of file qcustomplot.h.
Referenced by draw(), QCPItemCurve(), selectTest(), and MainWindow::setupItemDemo().
QCPLineEnding QCPItemCurve::mHead protected
Definition at line 3357 of file qcustomplot.h.
Referenced by draw(), and setHead().
QPen QCPItemCurve::mPen protected
Definition at line 3356 of file qcustomplot.h.
Referenced by mainPen(), and setPen().
QPen QCPItemCurve::mSelectedPen protected
Definition at line 3356 of file qcustomplot.h.
Referenced by mainPen(), and setSelectedPen().
QCPLineEnding QCPItemCurve::mTail protected
Definition at line 3357 of file qcustomplot.h.
Referenced by draw(), and setTail().
QCPItemPosition* const QCPItemCurve::start
Definition at line 3349 of file qcustomplot.h.
Referenced by draw(), QCPItemCurve(), selectTest(), and MainWindow::setupItemDemo().
QCPItemPosition* const QCPItemCurve::startDir
Definition at line 3350 of file qcustomplot.h.
Referenced by draw(), QCPItemCurve(), selectTest(), and MainWindow::setupItemDemo().
The documentation for this class was generated from the following files:
src/qcustomplot.h
src/qcustomplot.cpp