CheckImgLinearity: SwatchMainWindow Class Reference
SwatchMainWindow Class Reference
#include <SwatchMainWindow.h>
Classes
class Private
Public Types
typedef QVector< double > GraphData1D
typedef QPair< GraphData1D,
GraphData1D > GraphData2D
Public Member Functions
SwatchMainWindow (QWidget *parent=0)
virtual ~SwatchMainWindow ()
virtual void keyPressEvent (QKeyEvent *event)
virtual void resizeEvent (QResizeEvent *event)
ImagePlugin * getImgPlugin ()
Protected Member Functions
void createConnexionsMenu ()
bool loadColorWatchSettings (QString iniFile)
bool openImage (QString)
void switchImageSDKandReset (QAction *actFromMenuSDK)
void createGraph (GraphData2D graphRef, GraphData2D graphR, GraphData2D graphG, GraphData2D graphB, GraphData2D graphA)
Private Attributes
Private * d
Detailed Description
Definition at line 10 of file SwatchMainWindow.h.
Member Typedef Documentation
typedef QVector<double> SwatchMainWindow::GraphData1D
Definition at line 14 of file SwatchMainWindow.h.
typedef QPair<GraphData1D,GraphData1D> SwatchMainWindow::GraphData2D
Definition at line 15 of file SwatchMainWindow.h.
Constructor & Destructor Documentation
SwatchMainWindow::SwatchMainWindow (QWidget * parent = 0) explicit
Definition at line 37 of file SwatchMainWindow.cpp.
References createConnexionsMenu(), d, SwatchMainWindow::Private::mTitle, and SwatchMainWindow::Private::mUi.
SwatchMainWindow::~SwatchMainWindow () virtual
Definition at line 56 of file SwatchMainWindow.cpp.
References d.
Member Function Documentation
void SwatchMainWindow::createConnexionsMenu () protected
Definition at line 131 of file SwatchMainWindow.cpp.
References d, and SwatchMainWindow::Private::mUi.
Referenced by SwatchMainWindow().
void SwatchMainWindow::createGraph (GraphData2D graphRef, GraphData2D graphR, GraphData2D graphG, GraphData2D graphB, GraphData2D graphA) protected
Definition at line 287 of file SwatchMainWindow.cpp.
References d, QCP::iRangeDrag, QCP::iRangeZoom, QCP::iSelectPlottables, and SwatchMainWindow::Private::mUi.
Referenced by loadColorWatchSettings().
ImagePlugin * SwatchMainWindow::getImgPlugin ()
Definition at line 63 of file SwatchMainWindow.cpp.
References d, and SwatchMainWindow::Private::mImgPlg.
void SwatchMainWindow::keyPressEvent (QKeyEvent * event) virtual
Definition at line 228 of file SwatchMainWindow.cpp.
References d, SwatchMainWindow::Private::mImgPlg, and SwatchMainWindow::Private::mUi.
bool SwatchMainWindow::loadColorWatchSettings (QString iniFile) protected
Definition at line 70 of file SwatchMainWindow.cpp.
References ColorSwatch::A, ColorSwatch::B, createGraph(), d, ColorSwatch::G, SwatchMainWindow::Private::mColorSwatch, SwatchMainWindow::Private::mImgPlg, SwatchMainWindow::Private::mLoadedSettingsFilePath, SwatchMainWindow::Private::mUi, ColorSwatch::R, and ColorSwatch::REF.
Referenced by switchImageSDKandReset().
bool SwatchMainWindow::openImage (QString) protected
Definition at line 110 of file SwatchMainWindow.cpp.
References d, SwatchMainWindow::Private::mColorSwatch, SwatchMainWindow::Private::mImgPlg, SwatchMainWindow::Private::mOpenedImgFilePath, and SwatchMainWindow::Private::mUi.
Referenced by switchImageSDKandReset().
void SwatchMainWindow::resizeEvent (QResizeEvent * event) virtual
Definition at line 269 of file SwatchMainWindow.cpp.
References d, SwatchMainWindow::Private::mColorSwatch, SwatchMainWindow::Private::mImgPlg, SwatchMainWindow::Private::mLoadedSettingsFilePath, SwatchMainWindow::Private::mOpenedImgFilePath, and SwatchMainWindow::Private::mUi.
void SwatchMainWindow::switchImageSDKandReset (QAction * actFromMenuSDK) protected
Definition at line 200 of file SwatchMainWindow.cpp.
References d, loadColorWatchSettings(), SwatchMainWindow::Private::mLoadedSettingsFilePath, SwatchMainWindow::Private::mOpenedImgFilePath, SwatchMainWindow::Private::mUi, and openImage().
Member Data Documentation
Private* SwatchMainWindow::d private
Definition at line 41 of file SwatchMainWindow.h.
Referenced by createConnexionsMenu(), createGraph(), getImgPlugin(), keyPressEvent(), loadColorWatchSettings(), openImage(), resizeEvent(), SwatchMainWindow(), switchImageSDKandReset(), and ~SwatchMainWindow().
The documentation for this class was generated from the following files:
src/SwatchMainWindow.h
src/SwatchMainWindow.cpp