CheckImgLinearity: QCPItemRect Class Reference
QCPItemRect Class Reference
A rectangle.
#include <qcustomplot.h>
Public Member Functions
QCPItemRect (QCustomPlot *parentPlot)
Creates a rectangle item and sets default values.
virtual ~QCPItemRect ()
QPen pen () const
QPen selectedPen () const
QBrush brush () const
QBrush selectedBrush () const
void setPen (const QPen &pen)
Sets the pen that will be used to draw the line of the rectangle.
void setSelectedPen (const QPen &pen)
Sets the pen that will be used to draw the line of the rectangle when selected.
void setBrush (const QBrush &brush)
Sets the brush that will be used to fill the rectangle.
void setSelectedBrush (const QBrush &brush)
Sets the brush that will be used to fill the rectangle when selected.
virtual double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const
This function is used to decide whether a click hits a layerable object or not.
Public Member Functions inherited from QCPAbstractItem
QCPAbstractItem (QCustomPlot *parentPlot)
Base class constructor which initializes base class members.
virtual ~QCPAbstractItem ()
bool clipToAxisRect () const
QCPAxisRect * clipAxisRect () const
bool selectable () const
bool selected () const
void setClipToAxisRect (bool clip)
Sets whether the item shall be clipped to an axis rect or whether it shall be visible on the entire QCustomPlot.
void setClipAxisRect (QCPAxisRect *rect)
Sets the clip axis rect.
Q_SLOT void setSelectable (bool selectable)
Sets whether the user can (de-)select this item by clicking on the QCustomPlot surface.
Q_SLOT void setSelected (bool selected)
Sets whether this item is selected or not.
QList< QCPItemPosition * > positions () const
Returns all positions of the item in a list.
QList< QCPItemAnchor * > anchors () const
Returns all anchors of the item in a list.
QCPItemPosition * position (const QString &name) const
Returns the QCPItemPosition with the specified name.
QCPItemAnchor * anchor (const QString &name) const
Returns the QCPItemAnchor with the specified name.
bool hasAnchor (const QString &name) const
Returns whether this item has an anchor with the specified name.
Public Member Functions inherited from QCPLayerable
QCPLayerable (QCustomPlot *plot, QString targetLayer=QString(), QCPLayerable *parentLayerable=0)
Creates a new QCPLayerable instance.
~QCPLayerable ()
bool visible () const
QCustomPlot * parentPlot () const
QCPLayerable * parentLayerable () const
Returns the parent layerable of this layerable.
QCPLayer * layer () const
bool antialiased () const
void setVisible (bool on)
Sets the visibility of this layerable object.
Q_SLOT bool setLayer (QCPLayer *layer)
Sets the layer of this layerable object.
bool setLayer (const QString &layerName)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Sets the layer of this layerable object by name.
void setAntialiased (bool enabled)
Sets whether this object will be drawn antialiased or not.
bool realVisibility () const
Returns whether this layerable is visible, taking the visibility of the layerable parent and the visibility of the layer this layerable is on into account.
Public Attributes
QCPItemPosition *const topLeft
QCPItemPosition *const bottomRight
QCPItemAnchor *const top
QCPItemAnchor *const topRight
QCPItemAnchor *const right
QCPItemAnchor *const bottom
QCPItemAnchor *const bottomLeft
QCPItemAnchor *const left
Protected Types
enum AnchorIndex {
aiTop, aiTopRight, aiRight, aiBottom,
aiBottomLeft, aiLeft
}
Protected Member Functions
virtual void draw (QCPPainter *painter)
virtual QPointF anchorPixelPoint (int anchorId) const
QPen mainPen () const
QBrush mainBrush () const
Protected Member Functions inherited from QCPAbstractItem
virtual QCP::Interaction selectionCategory () const
virtual QRect clipRect () const
virtual void applyDefaultAntialiasingHint (QCPPainter *painter) const
virtual void selectEvent (QMouseEvent *event, bool additive, const QVariant &details, bool *selectionStateChanged)
virtual void deselectEvent (bool *selectionStateChanged)
double distSqrToLine (const QPointF &start, const QPointF &end, const QPointF &point) const
double rectSelectTest (const QRectF &rect, const QPointF &pos, bool filledRect) const
QCPItemPosition * createPosition (const QString &name)
QCPItemAnchor * createAnchor (const QString &name, int anchorId)
Protected Member Functions inherited from QCPLayerable
virtual void parentPlotInitialized (QCustomPlot *parentPlot)
void initializeParentPlot (QCustomPlot *parentPlot)
void setParentLayerable (QCPLayerable *parentLayerable)
bool moveToLayer (QCPLayer *layer, bool prepend)
void applyAntialiasingHint (QCPPainter *painter, bool localAntialiased, QCP::AntialiasedElement overrideElement) const
Protected Attributes
QPen mPen
QPen mSelectedPen
QBrush mBrush
QBrush mSelectedBrush
Protected Attributes inherited from QCPAbstractItem
bool mClipToAxisRect
QPointer< QCPAxisRect > mClipAxisRect
QList< QCPItemPosition * > mPositions
QList< QCPItemAnchor * > mAnchors
bool mSelectable
bool mSelected
Protected Attributes inherited from QCPLayerable
bool mVisible
QCustomPlot * mParentPlot
QPointer< QCPLayerable > mParentLayerable
QCPLayer * mLayer
bool mAntialiased
Additional Inherited Members
Signals inherited from QCPAbstractItem
void selectionChanged (bool selected)
This signal is emitted when the selection state of this item has changed, either by user interaction or by a direct call to setSelected.
void selectableChanged (bool selectable)
Signals inherited from QCPLayerable
void layerChanged (QCPLayer *newLayer)
This signal is emitted when the layer of this layerable changes, i.e.
Detailed Description
A rectangle.
Rectangle example. Blue dotted circles are anchors, solid blue discs are positions.
It has two positions, topLeft and bottomRight, which define the rectangle.
Definition at line 3367 of file qcustomplot.h.
Member Enumeration Documentation
enum QCPItemRect::AnchorIndex protected
Enumerator
aiTop
aiTopRight
aiRight
aiBottom
aiBottomLeft
aiLeft
Definition at line 3405 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPItemRect::QCPItemRect (QCustomPlot * parentPlot)
Creates a rectangle item and sets default values.
The constructed item can be added to the plot with QCustomPlot::addItem.
Definition at line 21974 of file qcustomplot.cpp.
References bottomRight, setBrush(), QCPItemPosition::setCoords(), setPen(), setSelectedBrush(), setSelectedPen(), and topLeft.
QCPItemRect::~QCPItemRect () virtual
Definition at line 21994 of file qcustomplot.cpp.
Member Function Documentation
QPointF QCPItemRect::anchorPixelPoint (int anchorId) const protected virtual
Reimplemented from QCPAbstractItem.
Definition at line 22071 of file qcustomplot.cpp.
References aiBottom, aiBottomLeft, aiLeft, aiRight, aiTop, aiTopRight, bottomRight, QCPItemPosition::pixelPoint(), and topLeft.
QBrush QCPItemRect::brush () const inline
Definition at line 3383 of file qcustomplot.h.
Referenced by setBrush(), and setSelectedBrush().
void QCPItemRect::draw (QCPPainter * painter) protected virtual
Implements QCPAbstractItem.
Definition at line 22053 of file qcustomplot.cpp.
References bottomRight, QCPAbstractItem::clipRect(), mainBrush(), mainPen(), QCPItemPosition::pixelPoint(), QCPPainter::setPen(), and topLeft.
QBrush QCPItemRect::mainBrush () const protected
Definition at line 22103 of file qcustomplot.cpp.
References mBrush, QCPAbstractItem::mSelected, and mSelectedBrush.
Referenced by draw().
QPen QCPItemRect::mainPen () const protected
Definition at line 22093 of file qcustomplot.cpp.
References mPen, QCPAbstractItem::mSelected, and mSelectedPen.
Referenced by draw().
QPen QCPItemRect::pen () const inline
Definition at line 3381 of file qcustomplot.h.
Referenced by setPen(), and setSelectedPen().
QBrush QCPItemRect::selectedBrush () const inline
Definition at line 3384 of file qcustomplot.h.
QPen QCPItemRect::selectedPen () const inline
Definition at line 3382 of file qcustomplot.h.
double QCPItemRect::selectTest (const QPointF & pos, bool onlySelectable, QVariant * details = 0) const virtual
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the item is represented not by single lines but by an area like QCPItemRect or QCPItemText, a click inside the area returns a constant value greater zero (typically the selectionTolerance of the parent QCustomPlot multiplied by 0.99). If the click lies outside the area, this function returns -1.0.
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
You may pass 0 as details to indicate that you are not interested in those selection details.
See also
selectEvent, deselectEvent, QCustomPlot::setInteractions
Implements QCPAbstractItem.
Definition at line 22041 of file qcustomplot.cpp.
References bottomRight, mBrush, QCPAbstractItem::mSelectable, QCPItemPosition::pixelPoint(), QCPAbstractItem::rectSelectTest(), and topLeft.
void QCPItemRect::setBrush (const QBrush & brush)
Sets the brush that will be used to fill the rectangle.
To disable filling, set brush to Qt::NoBrush.
See also
setSelectedBrush, setPen
Definition at line 22024 of file qcustomplot.cpp.
References brush(), and mBrush.
Referenced by QCPItemRect().
void QCPItemRect::setPen (const QPen & pen)
Sets the pen that will be used to draw the line of the rectangle.
See also
setSelectedPen, setBrush
Definition at line 22003 of file qcustomplot.cpp.
References mPen, and pen().
Referenced by QCPItemRect().
void QCPItemRect::setSelectedBrush (const QBrush & brush)
Sets the brush that will be used to fill the rectangle when selected.
To disable filling, set brush to Qt::NoBrush.
See also
setBrush
Definition at line 22035 of file qcustomplot.cpp.
References brush(), and mSelectedBrush.
Referenced by QCPItemRect().
void QCPItemRect::setSelectedPen (const QPen & pen)
Sets the pen that will be used to draw the line of the rectangle when selected.
See also
setPen, setSelected
Definition at line 22013 of file qcustomplot.cpp.
References mSelectedPen, and pen().
Referenced by QCPItemRect().
Member Data Documentation
QCPItemAnchor* const QCPItemRect::bottom
Definition at line 3400 of file qcustomplot.h.
QCPItemAnchor* const QCPItemRect::bottomLeft
Definition at line 3401 of file qcustomplot.h.
QCPItemPosition* const QCPItemRect::bottomRight
Definition at line 3396 of file qcustomplot.h.
Referenced by anchorPixelPoint(), draw(), QCPItemRect(), and selectTest().
QCPItemAnchor* const QCPItemRect::left
Definition at line 3402 of file qcustomplot.h.
QBrush QCPItemRect::mBrush protected
Definition at line 3409 of file qcustomplot.h.
Referenced by mainBrush(), selectTest(), and setBrush().
QPen QCPItemRect::mPen protected
Definition at line 3408 of file qcustomplot.h.
Referenced by mainPen(), and setPen().
QBrush QCPItemRect::mSelectedBrush protected
Definition at line 3409 of file qcustomplot.h.
Referenced by mainBrush(), and setSelectedBrush().
QPen QCPItemRect::mSelectedPen protected
Definition at line 3408 of file qcustomplot.h.
Referenced by mainPen(), and setSelectedPen().
QCPItemAnchor* const QCPItemRect::right
Definition at line 3399 of file qcustomplot.h.
QCPItemAnchor* const QCPItemRect::top
Definition at line 3397 of file qcustomplot.h.
QCPItemPosition* const QCPItemRect::topLeft
Definition at line 3395 of file qcustomplot.h.
Referenced by anchorPixelPoint(), draw(), QCPItemRect(), and selectTest().
QCPItemAnchor* const QCPItemRect::topRight
Definition at line 3398 of file qcustomplot.h.
The documentation for this class was generated from the following files:
src/qcustomplot.h
src/qcustomplot.cpp