CheckImgLinearity: ColorSwatch Class Reference
ColorSwatch Class Reference
#include <ColorSwatch.h>
Classes
class Private
Public Types
enum DATA {
DATA::REF, DATA::R, DATA::G, DATA::B,
DATA::A
}
typedef QVector< double > GraphData1D
typedef QPair< GraphData1D,
GraphData1D > GraphData2D
Public Member Functions
ColorSwatch (ImagePlugin *imgPlg)
virtual ~ColorSwatch ()
bool loadSettings (QString iniFile)
return true or otherwise false and may throw an exception some predefined parameters/options are loaded here
bool loadImages ()
return true or otherwise false and may throw an exception it not only load the image mask filename but also try to apply (overlay) it/on the raw image to get filled mask
bool fillPatchesPixelsFromMask ()
when mask image loaded, try to extract patches samples (pixel origin, pixels content, channels averages) from defined (or autodetected background) and fill colorSwatchPatch data structure (averages are only used to get the right patches order but since it is computed by Qt, we don't fill it into colorSwatchPatch)
GraphData2D getGraphData (DATA datalist)
QString rawFilePathName () const
bool haveImage () const
bool haveMask () const
QImage getMaskImg () const
QImage getQImage () const
QString printPatchesInfo () const
QString printMaskInfo () const
Protected Member Functions
void writeImage2QImage ()
Private Attributes
Private * d
Friends
std::ostream & operator<< (std::ostream &stream, const ColorSwatch &colorSwatch)
Detailed Description
Definition at line 8 of file ColorSwatch.h.
Member Typedef Documentation
typedef QVector<double> ColorSwatch::GraphData1D
Definition at line 15 of file ColorSwatch.h.
typedef QPair<GraphData1D,GraphData1D> ColorSwatch::GraphData2D
Definition at line 16 of file ColorSwatch.h.
Member Enumeration Documentation
enum ColorSwatch::DATA strong
Enumerator
REF
R
G
B
A
Definition at line 17 of file ColorSwatch.h.
Constructor & Destructor Documentation
ColorSwatch::ColorSwatch (ImagePlugin * imgPlg)
Definition at line 37 of file ColorSwatch.cpp.
References d, and ColorSwatch::Private::mImgPlg.
ColorSwatch::~ColorSwatch () virtual
Definition at line 42 of file ColorSwatch.cpp.
References d, and ColorSwatch::Private::mPatchesList.
Member Function Documentation
bool ColorSwatch::fillPatchesPixelsFromMask ()
when mask image loaded, try to extract patches samples (pixel origin, pixels content, channels averages) from defined (or autodetected background) and fill colorSwatchPatch data structure (averages are only used to get the right patches order but since it is computed by Qt, we don't fill it into colorSwatchPatch)
Definition at line 283 of file ColorSwatch.cpp.
References ColorSwatchPatch::computeAverageRGBpixel(), d, FILE_LINE_FUNC_STR, ColorSwatch::Private::mImgPlg, ColorSwatch::Private::mMask, ColorSwatch::Private::mPatchesList, ImagePlugin::readSinglePixelChannel(), and writeImage2QImage().
ColorSwatch::GraphData2D ColorSwatch::getGraphData (DATA datalist)
Definition at line 423 of file ColorSwatch.cpp.
References A, B, d, G, ColorSwatchPatch::getAverageColor(), ColorSwatchPatch::getReflectance(), ColorSwatch::Private::mPatchesList, R, and REF.
QImage ColorSwatch::getMaskImg () const
Definition at line 250 of file ColorSwatch.cpp.
References d, and ColorSwatch::Private::mMask.
QImage ColorSwatch::getQImage () const
Definition at line 240 of file ColorSwatch.cpp.
References d, ColorSwatch::Private::mImgPlg, and ImagePlugin::toQImage().
bool ColorSwatch::haveImage () const
Definition at line 235 of file ColorSwatch.cpp.
References d, ColorSwatch::Private::mImgPlg, and ImagePlugin::toQImage().
bool ColorSwatch::haveMask () const
Definition at line 245 of file ColorSwatch.cpp.
References d, and ColorSwatch::Private::mMask.
bool ColorSwatch::loadImages ()
return true or otherwise false and may throw an exception it not only load the image mask filename but also try to apply (overlay) it/on the raw image to get filled mask
Definition at line 175 of file ColorSwatch.cpp.
References d, FILE_LINE_FUNC_STR, ImagePlugin::loadImage(), ColorSwatch::Private::mImgPlg, ColorSwatch::Private::mMask, ColorSwatch::Private::mRawFile, ImagePlugin::size(), ImagePlugin::toQImage(), and writeImage2QImage().
bool ColorSwatch::loadSettings (QString iniFile)
return true or otherwise false and may throw an exception some predefined parameters/options are loaded here
Definition at line 50 of file ColorSwatch.cpp.
References d, FILE_LINE_FUNC_STR, ColorSwatch::Private::mMask, ColorSwatch::Private::mPatchesList, and ColorSwatch::Private::mRawFile.
QString ColorSwatch::printMaskInfo () const
Definition at line 264 of file ColorSwatch.cpp.
References d, and ColorSwatch::Private::mMask.
Referenced by operator<<().
QString ColorSwatch::printPatchesInfo () const
Definition at line 255 of file ColorSwatch.cpp.
References d, and ColorSwatch::Private::mPatchesList.
Referenced by operator<<().
QString ColorSwatch::rawFilePathName () const
Definition at line 230 of file ColorSwatch.cpp.
References d, and ColorSwatch::Private::mRawFile.
Referenced by operator<<().
void ColorSwatch::writeImage2QImage () protected
Definition at line 481 of file ColorSwatch.cpp.
References d, and ColorSwatch::Private::mMask.
Referenced by fillPatchesPixelsFromMask(), and loadImages().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & stream, const ColorSwatch & colorSwatch) friend
Definition at line 273 of file ColorSwatch.cpp.
Member Data Documentation
Private* ColorSwatch::d private
Definition at line 54 of file ColorSwatch.h.
Referenced by ColorSwatch(), fillPatchesPixelsFromMask(), getGraphData(), getMaskImg(), getQImage(), haveImage(), haveMask(), loadImages(), loadSettings(), printMaskInfo(), printPatchesInfo(), rawFilePathName(), writeImage2QImage(), and ~ColorSwatch().
The documentation for this class was generated from the following files:
src/ColorSwatch.h
src/ColorSwatch.cpp