CheckImgLinearity: QCPAbstractLegendItem Class Reference
QCPAbstractLegendItem Class Reference abstract
The abstract base class for all entries in a QCPLegend.
#include <qcustomplot.h>
Signals
void selectionChanged (bool selected)
This signal is emitted when the selection state of this legend item has changed, either by user interaction or by a direct call to setSelected.
void selectableChanged (bool selectable)
Signals inherited from QCPLayerable
void layerChanged (QCPLayer *newLayer)
This signal is emitted when the layer of this layerable changes, i.e.
Public Member Functions
QCPAbstractLegendItem (QCPLegend *parent)
Constructs a QCPAbstractLegendItem and associates it with the QCPLegend parent.
QCPLegend * parentLegend () const
QFont font () const
QColor textColor () const
QFont selectedFont () const
QColor selectedTextColor () const
bool selectable () const
bool selected () const
void setFont (const QFont &font)
Sets the default font of this specific legend item to font.
void setTextColor (const QColor &color)
Sets the default text color of this specific legend item to color.
void setSelectedFont (const QFont &font)
When this legend item is selected, font is used to draw generic text, instead of the normal font set with setFont.
void setSelectedTextColor (const QColor &color)
When this legend item is selected, color is used to draw generic text, instead of the normal color set with setTextColor.
Q_SLOT void setSelectable (bool selectable)
Sets whether this specific legend item is selectable.
Q_SLOT void setSelected (bool selected)
Sets whether this specific legend item is selected.
virtual double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const
Layout elements are sensitive to events inside their outer rect.
Public Member Functions inherited from QCPLayoutElement
QCPLayoutElement (QCustomPlot *parentPlot=0)
Creates an instance of QCPLayoutElement and sets default values.
virtual ~QCPLayoutElement ()
QCPLayout * layout () const
Returns the parent layout of this layout element.
QRect rect () const
Returns the inner rect of this layout element.
QRect outerRect () const
QMargins margins () const
QMargins minimumMargins () const
QCP::MarginSides autoMargins () const
QSize minimumSize () const
QSize maximumSize () const
QCPMarginGroup * marginGroup (QCP::MarginSide side) const
QHash< QCP::MarginSide,
QCPMarginGroup * > marginGroups () const
void setOuterRect (const QRect &rect)
Sets the outer rect of this layout element.
void setMargins (const QMargins &margins)
Sets the margins of this layout element.
void setMinimumMargins (const QMargins &margins)
If setAutoMargins is enabled on some or all margins, this function is used to provide minimum values for those margins.
void setAutoMargins (QCP::MarginSides sides)
Sets on which sides the margin shall be calculated automatically.
void setMinimumSize (const QSize &size)
Sets the minimum size for the inner rect of this layout element.
void setMinimumSize (int width, int height)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Sets the minimum size for the inner rect of this layout element.
void setMaximumSize (const QSize &size)
Sets the maximum size for the inner rect of this layout element.
void setMaximumSize (int width, int height)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Sets the maximum size for the inner rect of this layout element.
void setMarginGroup (QCP::MarginSides sides, QCPMarginGroup *group)
Sets the margin group of the specified margin sides.
virtual void update (UpdatePhase phase)
Updates the layout element and sub-elements.
virtual QSize minimumSizeHint () const
Returns the minimum size this layout element (the inner rect) may be compressed to.
virtual QSize maximumSizeHint () const
Returns the maximum size this layout element (the inner rect) may be expanded to.
virtual QList< QCPLayoutElement * > elements (bool recursive) const
Returns a list of all child elements in this layout element.
Public Member Functions inherited from QCPLayerable
QCPLayerable (QCustomPlot *plot, QString targetLayer=QString(), QCPLayerable *parentLayerable=0)
Creates a new QCPLayerable instance.
~QCPLayerable ()
bool visible () const
QCustomPlot * parentPlot () const
QCPLayerable * parentLayerable () const
Returns the parent layerable of this layerable.
QCPLayer * layer () const
bool antialiased () const
void setVisible (bool on)
Sets the visibility of this layerable object.
Q_SLOT bool setLayer (QCPLayer *layer)
Sets the layer of this layerable object.
bool setLayer (const QString &layerName)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Sets the layer of this layerable object by name.
void setAntialiased (bool enabled)
Sets whether this object will be drawn antialiased or not.
bool realVisibility () const
Returns whether this layerable is visible, taking the visibility of the layerable parent and the visibility of the layer this layerable is on into account.
Protected Member Functions
virtual QCP::Interaction selectionCategory () const
virtual void applyDefaultAntialiasingHint (QCPPainter *painter) const
virtual QRect clipRect () const
virtual void draw (QCPPainter *painter)=0
virtual void selectEvent (QMouseEvent *event, bool additive, const QVariant &details, bool *selectionStateChanged)
virtual void deselectEvent (bool *selectionStateChanged)
Protected Member Functions inherited from QCPLayoutElement
virtual int calculateAutoMargin (QCP::MarginSide side)
virtual void mousePressEvent (QMouseEvent *event)
This event is called, if the mouse was pressed while being inside the outer rect of this layout element.
virtual void mouseMoveEvent (QMouseEvent *event)
This event is called, if the mouse is moved inside the outer rect of this layout element.
virtual void mouseReleaseEvent (QMouseEvent *event)
This event is called, if the mouse was previously pressed inside the outer rect of this layout element and is now released.
virtual void mouseDoubleClickEvent (QMouseEvent *event)
This event is called, if the mouse is double-clicked inside the outer rect of this layout element.
virtual void wheelEvent (QWheelEvent *event)
This event is called, if the mouse wheel is scrolled while the cursor is inside the rect of this layout element.
virtual void parentPlotInitialized (QCustomPlot *parentPlot)
Protected Member Functions inherited from QCPLayerable
void initializeParentPlot (QCustomPlot *parentPlot)
void setParentLayerable (QCPLayerable *parentLayerable)
bool moveToLayer (QCPLayer *layer, bool prepend)
void applyAntialiasingHint (QCPPainter *painter, bool localAntialiased, QCP::AntialiasedElement overrideElement) const
Protected Attributes
QCPLegend * mParentLegend
QFont mFont
QColor mTextColor
QFont mSelectedFont
QColor mSelectedTextColor
bool mSelectable
bool mSelected
Protected Attributes inherited from QCPLayoutElement
QCPLayout * mParentLayout
QSize mMinimumSize
QSize mMaximumSize
QRect mRect
QRect mOuterRect
QMargins mMargins
QMargins mMinimumMargins
QCP::MarginSides mAutoMargins
QHash< QCP::MarginSide,
QCPMarginGroup * > mMarginGroups
Protected Attributes inherited from QCPLayerable
bool mVisible
QCustomPlot * mParentPlot
QPointer< QCPLayerable > mParentLayerable
QCPLayer * mLayer
bool mAntialiased
Friends
class QCPLegend
Additional Inherited Members
Public Types inherited from QCPLayoutElement
enum UpdatePhase { upPreparation, upMargins, upLayout }
Defines the phases of the update process, that happens just before a replot.
Detailed Description
The abstract base class for all entries in a QCPLegend.
It defines a very basic interface for entries in a QCPLegend. For representing plottables in the legend, the subclass QCPPlottableLegendItem is more suitable.
Only derive directly from this class when you need absolute freedom (e.g. a custom legend entry that's not even associated with a plottable).
You must implement the following pure virtual functions:
draw (from QCPLayerable)
You inherit the following members you may use:
QCPLegend *mParentLegend A pointer to the parent QCPLegend.
QFont mFont The generic font of the item. You should use this font for all or at least the most prominent text of the item.
Definition at line 2081 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPAbstractLegendItem::QCPAbstractLegendItem (QCPLegend * parent) explicit
Constructs a QCPAbstractLegendItem and associates it with the QCPLegend parent.
This does not cause the item to be added to parent, so QCPLegend::addItem must be called separately.
Definition at line 12660 of file qcustomplot.cpp.
References QCPLayerable::setLayer(), and QCPLayoutElement::setMargins().
Member Function Documentation
void QCPAbstractLegendItem::applyDefaultAntialiasingHint (QCPPainter * painter) const protected virtual
Reimplemented from QCPLayoutElement.
Definition at line 12762 of file qcustomplot.cpp.
References QCP::aeLegendItems, QCPLayerable::applyAntialiasingHint(), and QCPLayerable::mAntialiased.
QRect QCPAbstractLegendItem::clipRect () const protected virtual
Reimplemented from QCPLayerable.
Definition at line 12768 of file qcustomplot.cpp.
References QCPLayoutElement::mOuterRect.
void QCPAbstractLegendItem::deselectEvent (bool * selectionStateChanged) protected virtual
Reimplemented from QCPLayerable.
Definition at line 12788 of file qcustomplot.cpp.
References mParentLegend, mSelectable, mSelected, QCPLegend::selectableParts(), setSelected(), and QCPLegend::spItems.
virtual void QCPAbstractLegendItem::draw (QCPPainter * painter) protected pure virtual
Reimplemented from QCPLayoutElement.
Implemented in QCPPlottableLegendItem.
QFont QCPAbstractLegendItem::font () const inline
Definition at line 2098 of file qcustomplot.h.
Referenced by setFont(), and setSelectedFont().
QCPLegend* QCPAbstractLegendItem::parentLegend () const inline
Definition at line 2097 of file qcustomplot.h.
bool QCPAbstractLegendItem::selectable () const inline
Definition at line 2102 of file qcustomplot.h.
Referenced by setSelectable().
void QCPAbstractLegendItem::selectableChanged (bool selectable) signal
Referenced by setSelectable().
bool QCPAbstractLegendItem::selected () const inline
Definition at line 2103 of file qcustomplot.h.
Referenced by QCPLegend::selectedParts(), and setSelected().
QFont QCPAbstractLegendItem::selectedFont () const inline
Definition at line 2100 of file qcustomplot.h.
QColor QCPAbstractLegendItem::selectedTextColor () const inline
Definition at line 2101 of file qcustomplot.h.
void QCPAbstractLegendItem::selectEvent (QMouseEvent * event, bool additive, const QVariant & details, bool * selectionStateChanged) protected virtual
Reimplemented from QCPLayerable.
Definition at line 12774 of file qcustomplot.cpp.
References mParentLegend, mSelectable, mSelected, QCPLegend::selectableParts(), setSelected(), and QCPLegend::spItems.
QCP::Interaction QCPAbstractLegendItem::selectionCategory () const protected virtual
Reimplemented from QCPLayerable.
Definition at line 13478 of file qcustomplot.cpp.
References QCP::iSelectLegend.
void QCPAbstractLegendItem::selectionChanged (bool selected) signal
This signal is emitted when the selection state of this legend item has changed, either by user interaction or by a direct call to setSelected.
Referenced by setSelected().
double QCPAbstractLegendItem::selectTest (const QPointF & pos, bool onlySelectable, QVariant * details = 0) const virtual
Layout elements are sensitive to events inside their outer rect.
If pos is within the outer rect, this method returns a value corresponding to 0.99 times the parent plot's selection tolerance. However, layout elements are not selectable by default. So if onlySelectable is true, -1.0 is returned.
See QCPLayerable::selectTest for a general explanation of this virtual method.
QCPLayoutElement subclasses may reimplement this method to provide more specific selection test behaviour.
Reimplemented from QCPLayoutElement.
Definition at line 12748 of file qcustomplot.cpp.
References mParentLegend, QCPLayerable::mParentPlot, QCPLayoutElement::mRect, mSelectable, QCPLegend::selectableParts(), QCustomPlot::selectionTolerance(), and QCPLegend::spItems.
void QCPAbstractLegendItem::setFont (const QFont & font)
Sets the default font of this specific legend item to font.
See also
setTextColor, QCPLegend::setFont
Definition at line 12679 of file qcustomplot.cpp.
References font(), and mFont.
Referenced by QCPLegend::setFont().
void QCPAbstractLegendItem::setSelectable (bool selectable)
Sets whether this specific legend item is selectable.
See also
setSelectedParts, QCustomPlot::setInteractions
Definition at line 12721 of file qcustomplot.cpp.
References mSelectable, selectable(), and selectableChanged().
void QCPAbstractLegendItem::setSelected (bool selected)
Sets whether this specific legend item is selected.
It is possible to set the selection state of this item by calling this function directly, even if setSelectable is set to false.
See also
setSelectableParts, QCustomPlot::setInteractions
Definition at line 12738 of file qcustomplot.cpp.
References mSelected, selected(), and selectionChanged().
Referenced by deselectEvent(), selectEvent(), and QCPLegend::setSelectedParts().
void QCPAbstractLegendItem::setSelectedFont (const QFont & font)
When this legend item is selected, font is used to draw generic text, instead of the normal font set with setFont.
See also
setFont, QCPLegend::setSelectedFont
Definition at line 12700 of file qcustomplot.cpp.
References font(), and mSelectedFont.
Referenced by QCPLegend::setSelectedFont().
void QCPAbstractLegendItem::setSelectedTextColor (const QColor & color)
When this legend item is selected, color is used to draw generic text, instead of the normal color set with setTextColor.
See also
setTextColor, QCPLegend::setSelectedTextColor
Definition at line 12711 of file qcustomplot.cpp.
References mSelectedTextColor.
Referenced by QCPLegend::setSelectedTextColor().
void QCPAbstractLegendItem::setTextColor (const QColor & color)
Sets the default text color of this specific legend item to color.
See also
setFont, QCPLegend::setTextColor
Definition at line 12689 of file qcustomplot.cpp.
References mTextColor.
Referenced by QCPLegend::setTextColor().
QColor QCPAbstractLegendItem::textColor () const inline
Definition at line 2099 of file qcustomplot.h.
Friends And Related Function Documentation
friend class QCPLegend friend
Definition at line 2141 of file qcustomplot.h.
Member Data Documentation
QFont QCPAbstractLegendItem::mFont protected
Definition at line 2123 of file qcustomplot.h.
Referenced by QCPPlottableLegendItem::getFont(), and setFont().
QCPLegend* QCPAbstractLegendItem::mParentLegend protected
Definition at line 2122 of file qcustomplot.h.
Referenced by deselectEvent(), QCPPlottableLegendItem::draw(), QCPPlottableLegendItem::getIconBorderPen(), QCPPlottableLegendItem::minimumSizeHint(), selectEvent(), and selectTest().
bool QCPAbstractLegendItem::mSelectable protected
Definition at line 2127 of file qcustomplot.h.
Referenced by deselectEvent(), selectEvent(), selectTest(), and setSelectable().
bool QCPAbstractLegendItem::mSelected protected
Definition at line 2127 of file qcustomplot.h.
Referenced by deselectEvent(), QCPPlottableLegendItem::getFont(), QCPPlottableLegendItem::getIconBorderPen(), QCPPlottableLegendItem::getTextColor(), selectEvent(), and setSelected().
QFont QCPAbstractLegendItem::mSelectedFont protected
Definition at line 2125 of file qcustomplot.h.
Referenced by QCPPlottableLegendItem::getFont(), and setSelectedFont().
QColor QCPAbstractLegendItem::mSelectedTextColor protected
Definition at line 2126 of file qcustomplot.h.
Referenced by QCPPlottableLegendItem::getTextColor(), and setSelectedTextColor().
QColor QCPAbstractLegendItem::mTextColor protected
Definition at line 2124 of file qcustomplot.h.
Referenced by QCPPlottableLegendItem::getTextColor(), and setTextColor().
The documentation for this class was generated from the following files:
src/qcustomplot.h
src/qcustomplot.cpp